import {
  existsSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { afterEach, beforeAll, describe, expect, it } from 'vitest';
import type { FlowDefinition } from '@trawlarr/core';
import type { DocumentPort } from '@trawlarr/engine';
import type { ProbeData } from '@trawlarr/plugin-api';
import type { JobPayload } from '../src/worker/job-payload.js';
import type { JobReport } from '../src/worker/run-payload.js';
import {
  AGENT_MODULE_URL,
  AgentFailure,
  createAgentHandle,
  forkAgent,
} from '../src/worker/agent-handle.js';
import { fakeTimers } from './fake-child.js';
import { probeFile } from '../src/probe/ffprobe.js';
import { RESERVED_DIR_NAME } from '../src/library/paths.js';
import { ffmpegAvailableSync } from '../../../test-support/tool-availability.js';

/**
 * The one test that forks a REAL agent process.
 *
 * Everything about the protocol is proved deterministically in
 * `agent-handle.test.ts` against a fake child. What only a real fork can
 * prove is the thing a comment cannot: that the job runs in a DIFFERENT
 * process — a detached one, in its own process group — and that the
 * document store round trip really crosses that boundary. Both are read
 * out of observable state (pids the child itself reported, its process
 * group as the kernel sees it, and its absence afterwards), never from log
 * text and never from elapsed time.
 */

const AGENT_DIST = join(process.cwd(), 'packages/server/dist/worker/agent.js');
const AGENT_SRC = join(process.cwd(), 'packages/server/src/worker/agent.ts');

/**
 * This suite forks a BUILT artifact, so `pnpm test` on its own proves
 * nothing about `src/` unless `pnpm build` ran first — and `tsc --build` is
 * incremental, so a deleted or stale output is not regenerated by accident.
 * Deliberately NOT gated on `existsSync`: a missing artifact must FAIL here,
 * loudly, rather than skip and report green.
 */
const assertBuiltAgentIsFresh = (): void => {
  if (!existsSync(AGENT_DIST)) {
    throw new Error(`${AGENT_DIST} does not exist. Run "pnpm build" before this suite.`);
  }
  const builtAt = statSync(AGENT_DIST).mtimeMs;
  const sourceAt = statSync(AGENT_SRC).mtimeMs;
  if (builtAt < sourceAt) {
    throw new Error(
      `${AGENT_DIST} (built ${new Date(builtAt).toISOString()}) is older than ` +
        `${AGENT_SRC} (${new Date(sourceAt).toISOString()}) — this suite would be forking ` +
        `STALE compiled output. Run "pnpm build" (or "tsc --build --force") first.`,
    );
  }
};

const NOW = 1_700_000_000_000;

const PROBE: ProbeData = {
  streams: [
    { index: 0, codec_type: 'video', codec_name: 'hevc', width: 320, height: 240 },
    { index: 1, codec_type: 'audio', codec_name: 'aac' },
  ],
  format: { duration: '2.0', size: '4096', bit_rate: '16384' },
};

const writePlugin = (code: string): string => {
  const abs = join(mkdtempSync(join(tmpdir(), 'trawlarr-agent-plugin-')), 'index.js');
  writeFileSync(abs, code, 'utf8');
  return abs;
};

const detailsSource = (name: string, outputs: string) => `
const details = () => ({
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(name)},
  style: { borderColor: '#000000' },
  tags: 'test',
  isStartPlugin: false,
  pType: '',
  sidebarPosition: 1,
  icon: 'faQuestion',
  inputs: [],
  outputs: ${outputs},
  requiresVersion: '1.0.0',
});
`;

/**
 * Records the identity of the process it is actually running in, through
 * `crudTransDBN` — i.e. through the daemon's own document store, over IPC.
 *
 * `pgid` is read from `/proc/self/stat` (field 5, after the parenthesised
 * comm): a process whose pgid equals its own pid is a process-group LEADER,
 * which is exactly what `detached: true` buys and what lets Task 6 kill a
 * worker's whole tree, ffmpeg included, with one signal.
 */
const identityPluginPath = (): string =>
  writePlugin(`
${detailsSource('Record Identity', "[{ number: 1, tooltip: 'recorded' }]")}

const pgidOf = () => {
  try {
    const stat = require('node:fs').readFileSync('/proc/self/stat', 'utf8');
    const fields = stat.slice(stat.lastIndexOf(')') + 2).split(' ');
    return Number(fields[2]);
  } catch (error) {
    return null;
  }
};

const plugin = async (args) => {
  await args.deps.crudTransDBN('TrawlarrAgentIdentity', 'insert', 'who', {
    pid: process.pid,
    ppid: process.ppid,
    pgid: pgidOf(),
  });
  return { outputNumber: 1, outputFileObj: { _id: args.inputFileObj._id }, variables: args.variables };
};

module.exports = { details, plugin };
`);

/**
 * Reads that same document back and branches on it, so the value has to
 * cross the boundary in BOTH directions for output 1 to be taken. This is
 * the `processedCheck` shape every skip-list community plugin uses.
 */
const readBackPluginPath = (): string =>
  writePlugin(`
${detailsSource('Read Back Identity', "[{ number: 1, tooltip: 'came back' }, { number: 2, tooltip: 'did not' }]")}

const plugin = async (args) => {
  const doc = await args.deps.crudTransDBN('TrawlarrAgentIdentity', 'getById', 'who', {});
  return {
    outputNumber: doc && doc.pid === process.pid ? 1 : 2,
    outputFileObj: { _id: args.inputFileObj._id },
    variables: args.variables,
  };
};

module.exports = { details, plugin };
`);

/** A plugin that takes the process down without warning, as third-party code can. */
const suddenExitPluginPath = (): string =>
  writePlugin(`
${detailsSource('Sudden Death', "[{ number: 1, tooltip: 'never taken' }]")}

const plugin = () => {
  process.exit(7);
};

module.exports = { details, plugin };
`);

/** A plugin that throws, which the agent must REPORT rather than die of. */
const throwingPluginPath = (): string =>
  writePlugin(`
${detailsSource('Explodes', "[{ number: 1, tooltip: 'never taken' }]")}

const plugin = () => {
  throw new Error('plugin exploded on purpose');
};

module.exports = { details, plugin };
`);

const flowThrough = (pluginPaths: string[]): FlowDefinition => ({
  nodes: [
    { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
    ...pluginPaths.map((path, index) => ({
      id: `n${String(index)}`,
      pluginId: path,
      pluginVersion: '1.0.0',
      inputs: {},
    })),
  ],
  edges: [
    { fromNodeId: 'start', outputNumber: 1, toNodeId: 'n0' },
    ...pluginPaths.slice(1).map((_, index) => ({
      fromNodeId: `n${String(index)}`,
      outputNumber: 1,
      toNodeId: `n${String(index + 1)}`,
    })),
  ],
});

const payloadFor = (flow: FlowDefinition): JobPayload => ({
  jobId: 'job-1',
  fileId: 'file-1',
  libraryId: 'lib-1',
  path: '/lib/movie.mkv',
  container: 'mkv',
  sizeBytes: 4096,
  originalSizeBytes: 4096,
  mtimeMs: NOW - 1000,
  ctimeMs: NOW - 1000,
  footprintId: '66:1234',
  state: 'running',
  holdUntilMs: null,
  discoveredAtMs: NOW - 5000,
  probe: PROBE,
  library: {
    id: 'lib-1',
    name: 'lib',
    roots: ['/lib'],
    extensions: ['mkv'],
    companionExtensions: ['srt'],
    stagingDir: null,
    trashDir: null,
    flowId: 'flow-1',
    allowHardlinked: false,
    enabled: true,
    pausedReason: null,
    userVariables: {},
    createdAt: NOW - 10_000,
  },
  flow: { id: 'flow-1', definition: flow, definitionHash: 'flow-hash' },
  workerClass: 'transcode',
  hardwareType: 'cpu',
  ffmpegPath: 'ffmpeg',
  ffprobePath: 'ffprobe',
  logPath: null,
  // Only first-party plugins here: nothing installed to resolve.
  pluginPaths: {},
});

/** The daemon side of the document store: a plain map, in THIS process. */
const recordingDocuments = () => {
  const docs = new Map<string, Record<string, unknown>>();
  const port: DocumentPort = {
    get: (collection, docId) => docs.get(`${collection}:${docId}`),
    insert: (collection, docId, data) => {
      docs.set(`${collection}:${docId}`, data);
    },
    update: (collection, docId, patch) => {
      docs.set(`${collection}:${docId}`, { ...docs.get(`${collection}:${docId}`), ...patch });
    },
    removeOne: (collection, docId) => {
      docs.delete(`${collection}:${docId}`);
    },
  };
  return { port, docs };
};

const handleFor = (documents: DocumentPort) =>
  createAgentHandle({
    id: 'w1',
    documents,
    onStep: () => {},
    onHeartbeat: () => {},
    onProgress: () => {},
    onLog: () => {},
    nowMs: () => Date.now(),
    // The seam substitutes only the PATH: this is the real production fork,
    // with its real `detached`/`stdio` options, pointed at the built agent
    // rather than at the `.js` sibling of this repo's TypeScript source.
    forkFn: () => forkAgent(AGENT_DIST),
  });

/** Whether pid is still a live process, read from the OS rather than inferred. */
const isAlive = (pid: number): boolean => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

const ownPgid = (): number | null => {
  try {
    const stat = readFileSync('/proc/self/stat', 'utf8');
    return Number(stat.slice(stat.lastIndexOf(')') + 2).split(' ')[2]);
  } catch {
    return null;
  }
};

describe('the forked worker agent', () => {
  beforeAll(() => {
    assertBuiltAgentIsFresh();
  });

  it('is wired to a module that exists next to its handle in the build output', () => {
    // `AGENT_MODULE_URL` resolves against THIS repo's source layout under
    // vitest, so the assertion that can be made here is the structural one:
    // production forks `agent.js` beside `agent-handle.js`, and the build
    // really does contain that pair.
    expect(basename(fileURLToPath(AGENT_MODULE_URL))).toBe(basename(AGENT_DIST));
    expect(existsSync(join(dirname(AGENT_DIST), 'agent-handle.js'))).toBe(true);
  });

  it('runs the job in a separate, detached process and round-trips the document store over IPC', async () => {
    const { port, docs } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([identityPluginPath(), readBackPluginPath()]);

    const report: JobReport = await handle.run(payloadFor(flow));

    expect(report.success).toBe(true);
    expect(report.steps.map((step) => step.nodeId)).toEqual(['start', 'n0', 'n1']);

    // Written by the plugin, in the child, THROUGH the daemon's port: the
    // document only exists here if the round trip crossed the boundary.
    const identity = docs.get('TrawlarrAgentIdentity:who') as {
      pid: number;
      ppid: number;
      pgid: number | null;
    };
    expect(identity).toBeDefined();

    // Genuinely another process — and OUR child, not something unrelated.
    expect(identity.pid).not.toBe(process.pid);
    expect(identity.ppid).toBe(process.pid);
    // ...and the pid the daemon believes it forked is the pid the child
    // itself observed, so the handle is talking to that same process.
    expect(handle.pid).toBe(identity.pid);

    // `detached: true` in one observable fact: the child leads its own
    // process group, so `kill(-pid)` reaches its whole tree and nothing
    // of ours. Without `detached` its pgid would be the daemon's.
    if (identity.pgid !== null) {
      expect(identity.pgid).toBe(identity.pid);
      expect(identity.pgid).not.toBe(ownPgid());
    }

    // The second node took output 1, which it can only do if the document
    // it read came BACK across the boundary with the value in it.
    expect(report.steps.at(-1)?.outputNumber).toBe(1);

    // And the process is gone afterwards, rather than left behind holding
    // a worker slot. Read after `exited` resolves, so no timing is involved.
    await expect(handle.exited).resolves.toBe(0);
    expect(isAlive(identity.pid)).toBe(false);
  }, 30_000);

  it('reports a child that vanishes mid-job as a vanished child, not as a failure it authored', async () => {
    const { port } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([suddenExitPluginPath()]);

    const failure = await handle.run(payloadFor(flow)).then(
      () => {
        throw new Error('expected the run to reject');
      },
      (error: unknown) => error as AgentFailure,
    );

    expect(failure).toBeInstanceOf(AgentFailure);
    // The distinction the daemon acts on: nothing authored this failure,
    // so there is no plugin error text to record — only the disappearance.
    expect(failure.reported).toBe(false);
    expect(failure.exitCode).toBe(7);
    await expect(handle.exited).resolves.toBe(7);
  }, 30_000);

  it('reports a plugin that throws as a failure the agent AUTHORED, and still exits', async () => {
    const { port } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([throwingPluginPath()]);

    // A plugin error is not an agent failure: `runPayload` folds it into a
    // report with `failed: true`, which is a completed run.
    const report = await handle.run(payloadFor(flow));
    expect(report.failed).toBe(true);
    expect(report.success).toBe(false);
    expect(report.error).toContain('plugin exploded on purpose');

    await expect(handle.exited).resolves.toBe(0);
    expect(isAlive(handle.pid ?? 0)).toBe(false);
  }, 30_000);
});

/**
 * CANCELLING a real forked worker.
 *
 * Everything above proves the boundary exists. This proves the one thing a
 * shape assertion cannot: that cancelling reaches processes we did not
 * spawn. `detached: true` with a bare-pid kill and `detached: true` with a
 * group kill are indistinguishable to any assertion about spawn options —
 * only liveness separates them, and the previous phase measured the
 * difference:
 *
 *   kill(-pid)  (the group) -> worker dead, grandchild dead   <- the fix
 *   kill(pid)   (bare pid)  -> worker dead, grandchild ALIVE  <- the bug
 *
 * So every assertion here is `process.kill(pid, 0)` (which throws ESRCH once
 * a pid is gone), the kernel's own view of a process group read from
 * `/proc`, or a directory listing. Nothing reads log text, and nothing
 * measures elapsed time: the grace period is an INJECTED timer, advanced by
 * hand, because a test that really waits 30 seconds is a test nobody runs.
 *
 * Skipped on exactly ONE condition — a platform with no POSIX process
 * groups, where `kill(-pgid)`, `detached` and signal 0 have no meaning at
 * all — computed synchronously at module scope, because `skipIf` is
 * evaluated at collection time and a check behind an async `beforeAll` reads
 * as "skip" every run. Everything else is ASSERTED rather than detected: a
 * missing `/bin/sh` or `/proc` on a POSIX host is a broken environment, and
 * quietly removing this coverage is worse than failing.
 */
const posixProcessGroups = process.platform !== 'win32';

if (posixProcessGroups && !(existsSync('/bin/sh') && existsSync('/proc/self/stat'))) {
  throw new Error(
    'A POSIX host without /bin/sh or /proc cannot observe process groups: refusing to ' +
      'skip the worker cancellation suite silently.',
  );
}

const DEADLINE_MS = 15_000;

/** Polls until `predicate` holds, or fails with `what` — never a bare sleep. */
const until = async (what: string, predicate: () => boolean): Promise<void> => {
  const deadline = Date.now() + DEADLINE_MS;
  while (!predicate()) {
    if (Date.now() > deadline) throw new Error(`Timed out waiting for ${what}.`);
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
};

/** The process group a pid belongs to, as the kernel reports it. */
const pgidOfPid = (pid: number): number | null => {
  try {
    const stat = readFileSync(`/proc/${String(pid)}/stat`, 'utf8');
    return Number(stat.slice(stat.lastIndexOf(')') + 2).split(' ')[2]);
  } catch {
    return null;
  }
};

/** Every live process descended from `pid`, however deep. */
const descendantsOf = (pid: number): number[] => {
  const parentOf = new Map<number, number>();
  for (const entry of readdirSync('/proc')) {
    const candidate = Number(entry);
    if (!Number.isInteger(candidate)) continue;
    try {
      const stat = readFileSync(`/proc/${entry}/stat`, 'utf8');
      parentOf.set(candidate, Number(stat.slice(stat.lastIndexOf(')') + 2).split(' ')[1]));
    } catch {
      // The process exited between readdir and read: not a descendant now.
    }
  }
  const found: number[] = [];
  let frontier = [pid];
  while (frontier.length > 0) {
    const next: number[] = [];
    for (const [child, parent] of parentOf) {
      if (!frontier.includes(parent) || found.includes(child)) continue;
      found.push(child);
      next.push(child);
    }
    frontier = next;
  }
  return found;
};

/** The command name of a pid, for picking the real ffmpeg out of a tree. */
const commOf = (pid: number): string => {
  try {
    return readFileSync(`/proc/${String(pid)}/comm`, 'utf8').trim();
  } catch {
    return '';
  }
};

/**
 * A plugin that spawns a REAL descendant of its own, outside the runner, and
 * then never returns.
 *
 * This is the whole scenario in one file: a third-party plugin free to shell
 * out to ffmpeg itself. The descendant is NOT detached, so it inherits the
 * worker's process group — which is what a group kill reaches and a bare-pid
 * kill does not. It `trap`s SIGTERM (as ffmpeg legitimately does while
 * finalising a container) so only SIGKILL ends it, and the plugin awaits a
 * promise that never settles, so the agent's abort has nothing to unblock.
 */
const grandchildPluginPath = (pidFile: string): string =>
  writePlugin(`
${detailsSource('Spawns Its Own ffmpeg', "[{ number: 1, tooltip: 'never taken' }]")}

const { spawn } = require('node:child_process');

const plugin = async (args) => {
  spawn(
    '/bin/sh',
    [
      '-c',
      "trap '' TERM; echo $$ > ${pidFile}.tmp; mv ${pidFile}.tmp ${pidFile}; " +
        'while : ; do sleep 0.2; done',
    ],
    { stdio: 'ignore' },
  );
  await new Promise(() => {});
  return { outputNumber: 1, outputFileObj: { _id: args.inputFileObj._id }, variables: args.variables };
};

module.exports = { details, plugin };
`);

/** Pids this suite caused to exist, swept regardless of whether the code worked. */
const causedPids: number[] = [];

/** A real pid, killed for real — recorded so the test can assert on it. */
const recordingKill = (kills: { pid: number; signal: NodeJS.Signals }[]) => {
  return (pid: number, signal: NodeJS.Signals): void => {
    kills.push({ pid, signal });
    process.kill(pid, signal);
  };
};

const readGrandchildPid = (pidFile: string): number => {
  const text = readFileSync(pidFile, 'utf8').trim();
  const pid = Number.parseInt(text, 10);
  if (!Number.isInteger(pid) || pid <= 1) throw new Error(`Unusable grandchild pid: "${text}"`);
  return pid;
};

describe.skipIf(!posixProcessGroups)('cancelling a real forked worker', () => {
  beforeAll(() => {
    assertBuiltAgentIsFresh();
  });

  afterEach(() => {
    // Cleanup must not depend on the code under test having worked: on a
    // FAILING run, the tree the kill failed to take down is exactly what is
    // still running here.
    for (const pid of causedPids.splice(0)) {
      try {
        process.kill(-pid, 'SIGKILL');
      } catch {
        // Already gone, or never a group leader.
      }
      try {
        process.kill(pid, 'SIGKILL');
      } catch {
        // Already gone.
      }
    }
  });

  it('kills a grandchild the PLUGIN spawned, not just the worker process', async () => {
    const pidFile = join(mkdtempSync(join(tmpdir(), 'trawlarr-cancel-')), 'grandchild.pid');
    const { port } = recordingDocuments();
    const timers = fakeTimers();
    const kills: { pid: number; signal: NodeJS.Signals }[] = [];
    const handle = createAgentHandle({
      id: 'w1',
      documents: port,
      onStep: () => {},
      onHeartbeat: () => {},
      onProgress: () => {},
      onLog: () => {},
      nowMs: () => Date.now(),
      forkFn: () => forkAgent(AGENT_DIST),
      killFn: recordingKill(kills),
      setTimer: timers.setTimer,
      clearTimer: timers.clearTimer,
    });

    const running = handle.run(payloadFor(flowThrough([grandchildPluginPath(pidFile)])));
    // Nothing may reject unobserved while the assertions below run.
    const outcome = running.then(
      () => null,
      (error: unknown) => error as AgentFailure,
    );

    const worker = handle.pid;
    if (worker === undefined) throw new Error('The forked worker never got a pid.');
    causedPids.push(worker);

    let grandchild = 0;
    await until('the plugin to report the pid of the process it spawned', () => {
      try {
        grandchild = readGrandchildPid(pidFile);
        return true;
      } catch {
        return false;
      }
    });
    causedPids.push(grandchild);

    expect(isAlive(worker)).toBe(true);
    expect(isAlive(grandchild)).toBe(true);
    expect(grandchild).not.toBe(worker);
    // The property that makes ONE signal sufficient: the process the plugin
    // spawned is in the worker's group, and the worker leads that group.
    expect(pgidOfPid(worker)).toBe(worker);
    expect(pgidOfPid(grandchild)).toBe(worker);

    handle.cancel();
    // Rung one: asked politely, signalled not at all.
    expect(kills).toEqual([]);

    timers.advance(30_000);
    // Rung two, NEGATED: the group, not the pid. This is the assertion that
    // reverts to red if `killProcessGroup` is replaced by a bare-pid kill —
    // and so does the grandchild's death below.
    expect(kills).toEqual([{ pid: -worker, signal: 'SIGTERM' }]);

    // Liveness FIRST, before awaiting the run: under a bare-pid kill the
    // surviving grandchild is a specific, named failure here, rather than an
    // unexplained suite timeout somewhere later.
    await until('the worker process to be gone', () => !isAlive(worker));
    await until('the process the plugin spawned to be gone', () => !isAlive(grandchild));
    expect(isAlive(grandchild)).toBe(false);
    expect(isAlive(worker)).toBe(false);
    // Nothing of the worker's tree survives it.
    expect(descendantsOf(process.pid)).not.toContain(grandchild);

    const failure = await outcome;
    expect(failure).toBeInstanceOf(AgentFailure);
    expect(failure?.cancelled).toBe(true);
  }, 60_000);
});

/**
 * The same cancellation against REAL ffmpeg, on the rung that should
 * normally be enough: the worker is asked to stop, its own runner takes the
 * transcode down, and the daemon never has to escalate.
 *
 * Gated on ffmpeg being installed — checked SYNCHRONOUSLY at module scope,
 * because `skipIf` is evaluated at collection time and a check behind an
 * async `beforeAll` reads as "skip" on every run, which is exactly how this
 * repo's end-to-end suite silently skipped for several commits. Only ENOENT
 * counts as "not installed"; a check that could not be trusted throws (see
 * `toolAvailableSync`).
 */
const ffmpegPresent = ffmpegAvailableSync();

const makeLongSample = (path: string): void => {
  execFileSync(
    'ffmpeg',
    [
      '-hide_banner',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=60:size=640x480:rate=24',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      path,
    ],
    { stdio: 'ignore' },
  );
};

const TRANSCODE_FLOW: FlowDefinition = {
  nodes: [
    { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
    { id: 'begin', pluginId: 'trawlarr:beginCommand', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'encoder',
      pluginId: 'trawlarr:setVideoEncoder',
      pluginVersion: '1.0.0',
      inputs: { encoder: 'libx265', quality: '30' },
    },
    { id: 'execute', pluginId: 'trawlarr:execute', pluginVersion: '1.0.0', inputs: {} },
  ],
  edges: [
    { fromNodeId: 'start', outputNumber: 1, toNodeId: 'begin' },
    { fromNodeId: 'begin', outputNumber: 1, toNodeId: 'encoder' },
    { fromNodeId: 'encoder', outputNumber: 1, toNodeId: 'execute' },
  ],
};

describe.skipIf(!posixProcessGroups || !ffmpegPresent)(
  'cancelling a real transcode in a real worker',
  () => {
    beforeAll(() => {
      assertBuiltAgentIsFresh();
    });

    afterEach(() => {
      for (const pid of causedPids.splice(0)) {
        try {
          process.kill(-pid, 'SIGKILL');
        } catch {
          // Already gone, or never a group leader.
        }
        try {
          process.kill(pid, 'SIGKILL');
        } catch {
          // Already gone.
        }
      }
    });

    it('stops ffmpeg and cleans up its staged output without the daemon signalling anything', async () => {
      const libDir = mkdtempSync(join(tmpdir(), 'trawlarr-cancel-lib-'));
      const filePath = join(libDir, 'movie.mkv');
      makeLongSample(filePath);
      const probe = await probeFile({ ffprobePath: 'ffprobe', path: filePath });

      // The worker builds its scratch directory INSIDE the library it is
      // working on — `<root>/.trawlarr/staging`, from `resolveStagingDir` —
      // so that installing a finished encode is a rename(2) and can never be
      // a cross-device copy. That is therefore where a cancelled job's
      // half-written output has to be cleaned up from, and this library root
      // is private to this test, which is what makes "did the staged output
      // get cleaned up" an assertion about THIS worker.
      const workRoot = join(libDir, RESERVED_DIR_NAME, 'staging');

      const { port } = recordingDocuments();
      const timers = fakeTimers();
      const kills: { pid: number; signal: NodeJS.Signals }[] = [];
      const handle = createAgentHandle({
        id: 'w1',
        documents: port,
        onStep: () => {},
        onHeartbeat: () => {},
        onProgress: () => {},
        onLog: () => {},
        nowMs: () => Date.now(),
        forkFn: () => forkAgent(AGENT_DIST),
        killFn: recordingKill(kills),
        setTimer: timers.setTimer,
        clearTimer: timers.clearTimer,
      });

      const base = payloadFor(TRANSCODE_FLOW);
      const running = handle.run({
        ...base,
        path: filePath,
        sizeBytes: statSync(filePath).size,
        originalSizeBytes: statSync(filePath).size,
        probe,
        library: { ...base.library, roots: [libDir] },
      });
      const outcome = running.then(
        (report) => ({ report, failure: null }),
        (error: unknown) => ({ report: null, failure: error as AgentFailure }),
      );

      const worker = handle.pid;
      if (worker === undefined) throw new Error('The forked worker never got a pid.');
      causedPids.push(worker);

      // A real ffmpeg, spawned by the worker's own runner, encoding right now.
      let ffmpeg = 0;
      await until('ffmpeg to be running under the worker', () => {
        ffmpeg = descendantsOf(worker).find((pid) => commOf(pid).includes('ffmpeg')) ?? 0;
        return ffmpeg !== 0;
      });
      causedPids.push(ffmpeg);
      expect(isAlive(ffmpeg)).toBe(true);
      // The cleanup assertion at the end is only meaningful if there is
      // something to clean up: the worker's scratch directory, holding the
      // half-written encode, really is here while ffmpeg runs.
      expect(
        readdirSync(workRoot).filter((entry) => entry.startsWith('trawlarr-job-')),
      ).toHaveLength(1);

      handle.cancel();

      // Liveness first, as ever: ffmpeg and the worker are both gone, and
      // the timers were never advanced, so NOTHING here depends on a clock.
      await until('the ffmpeg process to be gone', () => !isAlive(ffmpeg));
      await until('the worker process to be gone', () => !isAlive(worker));
      expect(isAlive(ffmpeg)).toBe(false);

      // The escalation was never needed: no SIGTERM was sent, because the
      // worker stopped when it was asked to. (The one signal that does go
      // out is the post-exit group sweep — see `agent-handle.ts`.)
      expect(kills.filter((kill) => kill.signal === 'SIGTERM')).toEqual([]);

      const { report, failure } = await outcome;
      expect(failure).toBeNull();
      expect(report?.cancelled).toBe(true);

      // Cleanup: no staged output and no work directory left behind, and the
      // library file itself untouched — a cancelled job leaves nothing for
      // the next run to trip over.
      expect(readdirSync(workRoot)).toEqual([]);
      // `.trawlarr` is the reserved directory the staging dir above lives in;
      // it stays (empty) and is pruned from every scan by construction.
      expect(readdirSync(libDir).sort()).toEqual([RESERVED_DIR_NAME, 'movie.mkv']);
    }, 120_000);
  },
);
