import { existsSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, it } from 'vitest';
import type { FlowDefinition } from '@trawlarr/core';
import type { DocumentPort } from '@trawlarr/engine';
import type { ProbeData } from '@trawlarr/plugin-api';
import type { JobPayload } from '../src/worker/job-payload.js';
import type { JobReport } from '../src/worker/run-payload.js';
import {
  AGENT_MODULE_URL,
  AgentFailure,
  createAgentHandle,
  forkAgent,
} from '../src/worker/agent-handle.js';

/**
 * The one test that forks a REAL agent process.
 *
 * Everything about the protocol is proved deterministically in
 * `agent-handle.test.ts` against a fake child. What only a real fork can
 * prove is the thing a comment cannot: that the job runs in a DIFFERENT
 * process — a detached one, in its own process group — and that the
 * document store round trip really crosses that boundary. Both are read
 * out of observable state (pids the child itself reported, its process
 * group as the kernel sees it, and its absence afterwards), never from log
 * text and never from elapsed time.
 */

const AGENT_DIST = join(process.cwd(), 'packages/server/dist/worker/agent.js');
const AGENT_SRC = join(process.cwd(), 'packages/server/src/worker/agent.ts');

/**
 * This suite forks a BUILT artifact, so `pnpm test` on its own proves
 * nothing about `src/` unless `pnpm build` ran first — and `tsc --build` is
 * incremental, so a deleted or stale output is not regenerated by accident.
 * Deliberately NOT gated on `existsSync`: a missing artifact must FAIL here,
 * loudly, rather than skip and report green.
 */
const assertBuiltAgentIsFresh = (): void => {
  if (!existsSync(AGENT_DIST)) {
    throw new Error(`${AGENT_DIST} does not exist. Run "pnpm build" before this suite.`);
  }
  const builtAt = statSync(AGENT_DIST).mtimeMs;
  const sourceAt = statSync(AGENT_SRC).mtimeMs;
  if (builtAt < sourceAt) {
    throw new Error(
      `${AGENT_DIST} (built ${new Date(builtAt).toISOString()}) is older than ` +
        `${AGENT_SRC} (${new Date(sourceAt).toISOString()}) — this suite would be forking ` +
        `STALE compiled output. Run "pnpm build" (or "tsc --build --force") first.`,
    );
  }
};

const NOW = 1_700_000_000_000;

const PROBE: ProbeData = {
  streams: [
    { index: 0, codec_type: 'video', codec_name: 'hevc', width: 320, height: 240 },
    { index: 1, codec_type: 'audio', codec_name: 'aac' },
  ],
  format: { duration: '2.0', size: '4096', bit_rate: '16384' },
};

const writePlugin = (code: string): string => {
  const abs = join(mkdtempSync(join(tmpdir(), 'trawlarr-agent-plugin-')), 'index.js');
  writeFileSync(abs, code, 'utf8');
  return abs;
};

const detailsSource = (name: string, outputs: string) => `
const details = () => ({
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(name)},
  style: { borderColor: '#000000' },
  tags: 'test',
  isStartPlugin: false,
  pType: '',
  sidebarPosition: 1,
  icon: 'faQuestion',
  inputs: [],
  outputs: ${outputs},
  requiresVersion: '1.0.0',
});
`;

/**
 * Records the identity of the process it is actually running in, through
 * `crudTransDBN` — i.e. through the daemon's own document store, over IPC.
 *
 * `pgid` is read from `/proc/self/stat` (field 5, after the parenthesised
 * comm): a process whose pgid equals its own pid is a process-group LEADER,
 * which is exactly what `detached: true` buys and what lets Task 6 kill a
 * worker's whole tree, ffmpeg included, with one signal.
 */
const identityPluginPath = (): string =>
  writePlugin(`
${detailsSource('Record Identity', "[{ number: 1, tooltip: 'recorded' }]")}

const pgidOf = () => {
  try {
    const stat = require('node:fs').readFileSync('/proc/self/stat', 'utf8');
    const fields = stat.slice(stat.lastIndexOf(')') + 2).split(' ');
    return Number(fields[2]);
  } catch (error) {
    return null;
  }
};

const plugin = async (args) => {
  await args.deps.crudTransDBN('TrawlarrAgentIdentity', 'insert', 'who', {
    pid: process.pid,
    ppid: process.ppid,
    pgid: pgidOf(),
  });
  return { outputNumber: 1, outputFileObj: { _id: args.inputFileObj._id }, variables: args.variables };
};

module.exports = { details, plugin };
`);

/**
 * Reads that same document back and branches on it, so the value has to
 * cross the boundary in BOTH directions for output 1 to be taken. This is
 * the `processedCheck` shape every skip-list community plugin uses.
 */
const readBackPluginPath = (): string =>
  writePlugin(`
${detailsSource('Read Back Identity', "[{ number: 1, tooltip: 'came back' }, { number: 2, tooltip: 'did not' }]")}

const plugin = async (args) => {
  const doc = await args.deps.crudTransDBN('TrawlarrAgentIdentity', 'getById', 'who', {});
  return {
    outputNumber: doc && doc.pid === process.pid ? 1 : 2,
    outputFileObj: { _id: args.inputFileObj._id },
    variables: args.variables,
  };
};

module.exports = { details, plugin };
`);

/** A plugin that takes the process down without warning, as third-party code can. */
const suddenExitPluginPath = (): string =>
  writePlugin(`
${detailsSource('Sudden Death', "[{ number: 1, tooltip: 'never taken' }]")}

const plugin = () => {
  process.exit(7);
};

module.exports = { details, plugin };
`);

/** A plugin that throws, which the agent must REPORT rather than die of. */
const throwingPluginPath = (): string =>
  writePlugin(`
${detailsSource('Explodes', "[{ number: 1, tooltip: 'never taken' }]")}

const plugin = () => {
  throw new Error('plugin exploded on purpose');
};

module.exports = { details, plugin };
`);

const flowThrough = (pluginPaths: string[]): FlowDefinition => ({
  nodes: [
    { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
    ...pluginPaths.map((path, index) => ({
      id: `n${String(index)}`,
      pluginId: path,
      pluginVersion: '1.0.0',
      inputs: {},
    })),
  ],
  edges: [
    { fromNodeId: 'start', outputNumber: 1, toNodeId: 'n0' },
    ...pluginPaths.slice(1).map((_, index) => ({
      fromNodeId: `n${String(index)}`,
      outputNumber: 1,
      toNodeId: `n${String(index + 1)}`,
    })),
  ],
});

const payloadFor = (flow: FlowDefinition): JobPayload => ({
  jobId: 'job-1',
  fileId: 'file-1',
  libraryId: 'lib-1',
  path: '/lib/movie.mkv',
  container: 'mkv',
  sizeBytes: 4096,
  originalSizeBytes: 4096,
  mtimeMs: NOW - 1000,
  ctimeMs: NOW - 1000,
  footprintId: '66:1234',
  state: 'running',
  holdUntilMs: null,
  discoveredAtMs: NOW - 5000,
  probe: PROBE,
  library: {
    id: 'lib-1',
    name: 'lib',
    roots: ['/lib'],
    extensions: ['mkv'],
    companionExtensions: ['srt'],
    stagingDir: null,
    trashDir: null,
    flowId: 'flow-1',
    allowHardlinked: false,
    enabled: true,
    pausedReason: null,
    userVariables: {},
    createdAt: NOW - 10_000,
  },
  flow: { id: 'flow-1', definition: flow, definitionHash: 'flow-hash' },
  workerClass: 'transcode',
  hardwareType: 'cpu',
  ffmpegPath: 'ffmpeg',
  ffprobePath: 'ffprobe',
});

/** The daemon side of the document store: a plain map, in THIS process. */
const recordingDocuments = () => {
  const docs = new Map<string, Record<string, unknown>>();
  const port: DocumentPort = {
    get: (collection, docId) => docs.get(`${collection}:${docId}`),
    insert: (collection, docId, data) => {
      docs.set(`${collection}:${docId}`, data);
    },
    update: (collection, docId, patch) => {
      docs.set(`${collection}:${docId}`, { ...docs.get(`${collection}:${docId}`), ...patch });
    },
    removeOne: (collection, docId) => {
      docs.delete(`${collection}:${docId}`);
    },
  };
  return { port, docs };
};

const handleFor = (documents: DocumentPort) =>
  createAgentHandle({
    id: 'w1',
    documents,
    onStep: () => {},
    onHeartbeat: () => {},
    onProgress: () => {},
    onLog: () => {},
    nowMs: () => Date.now(),
    // The seam substitutes only the PATH: this is the real production fork,
    // with its real `detached`/`stdio` options, pointed at the built agent
    // rather than at the `.js` sibling of this repo's TypeScript source.
    forkFn: () => forkAgent(AGENT_DIST),
  });

/** Whether pid is still a live process, read from the OS rather than inferred. */
const isAlive = (pid: number): boolean => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

const ownPgid = (): number | null => {
  try {
    const stat = readFileSync('/proc/self/stat', 'utf8');
    return Number(stat.slice(stat.lastIndexOf(')') + 2).split(' ')[2]);
  } catch {
    return null;
  }
};

describe('the forked worker agent', () => {
  beforeAll(() => {
    assertBuiltAgentIsFresh();
  });

  it('is wired to a module that exists next to its handle in the build output', () => {
    // `AGENT_MODULE_URL` resolves against THIS repo's source layout under
    // vitest, so the assertion that can be made here is the structural one:
    // production forks `agent.js` beside `agent-handle.js`, and the build
    // really does contain that pair.
    expect(basename(fileURLToPath(AGENT_MODULE_URL))).toBe(basename(AGENT_DIST));
    expect(existsSync(join(dirname(AGENT_DIST), 'agent-handle.js'))).toBe(true);
  });

  it('runs the job in a separate, detached process and round-trips the document store over IPC', async () => {
    const { port, docs } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([identityPluginPath(), readBackPluginPath()]);

    const report: JobReport = await handle.run(payloadFor(flow));

    expect(report.success).toBe(true);
    expect(report.steps.map((step) => step.nodeId)).toEqual(['start', 'n0', 'n1']);

    // Written by the plugin, in the child, THROUGH the daemon's port: the
    // document only exists here if the round trip crossed the boundary.
    const identity = docs.get('TrawlarrAgentIdentity:who') as {
      pid: number;
      ppid: number;
      pgid: number | null;
    };
    expect(identity).toBeDefined();

    // Genuinely another process — and OUR child, not something unrelated.
    expect(identity.pid).not.toBe(process.pid);
    expect(identity.ppid).toBe(process.pid);
    // ...and the pid the daemon believes it forked is the pid the child
    // itself observed, so the handle is talking to that same process.
    expect(handle.pid).toBe(identity.pid);

    // `detached: true` in one observable fact: the child leads its own
    // process group, so `kill(-pid)` reaches its whole tree and nothing
    // of ours. Without `detached` its pgid would be the daemon's.
    if (identity.pgid !== null) {
      expect(identity.pgid).toBe(identity.pid);
      expect(identity.pgid).not.toBe(ownPgid());
    }

    // The second node took output 1, which it can only do if the document
    // it read came BACK across the boundary with the value in it.
    expect(report.steps.at(-1)?.outputNumber).toBe(1);

    // And the process is gone afterwards, rather than left behind holding
    // a worker slot. Read after `exited` resolves, so no timing is involved.
    await expect(handle.exited).resolves.toBe(0);
    expect(isAlive(identity.pid)).toBe(false);
  }, 30_000);

  it('reports a child that vanishes mid-job as a vanished child, not as a failure it authored', async () => {
    const { port } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([suddenExitPluginPath()]);

    const failure = await handle.run(payloadFor(flow)).then(
      () => {
        throw new Error('expected the run to reject');
      },
      (error: unknown) => error as AgentFailure,
    );

    expect(failure).toBeInstanceOf(AgentFailure);
    // The distinction the daemon acts on: nothing authored this failure,
    // so there is no plugin error text to record — only the disappearance.
    expect(failure.reported).toBe(false);
    expect(failure.exitCode).toBe(7);
    await expect(handle.exited).resolves.toBe(7);
  }, 30_000);

  it('reports a plugin that throws as a failure the agent AUTHORED, and still exits', async () => {
    const { port } = recordingDocuments();
    const handle = handleFor(port);
    const flow = flowThrough([throwingPluginPath()]);

    // A plugin error is not an agent failure: `runPayload` folds it into a
    // report with `failed: true`, which is a completed run.
    const report = await handle.run(payloadFor(flow));
    expect(report.failed).toBe(true);
    expect(report.success).toBe(false);
    expect(report.error).toContain('plugin exploded on purpose');

    await expect(handle.exited).resolves.toBe(0);
    expect(isAlive(handle.pid ?? 0)).toBe(false);
  }, 30_000);
});
