import { execFile, spawn, type ChildProcess } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join } from 'node:path';
import { promisify } from 'node:util';
import { afterEach, describe, expect, it } from 'vitest';
import WebSocket from 'ws';
import type { FlowDefinition } from '@trawlarr/core';
import { openDatabase } from '../src/db/connection.js';
import { migrate } from '../src/db/migrate.js';
import { createSettingsRepo } from '../src/db/settings-repo.js';
import { createLibraryRepo } from '../src/db/library-repo.js';
import { createMediaFileRepo } from '../src/db/media-file-repo.js';
import { DAEMON_LOCK_FILENAME, type DaemonRecord } from '../src/daemon/lockfile.js';
import type { TrawlarrEvent } from '../src/daemon/events.js';
import { ffmpegAvailableSync } from '../../../test-support/tool-availability.js';

const execFileAsync = promisify(execFile);

/**
 * THE DAEMON CONVERGES A LIBRARY ON ITS OWN.
 *
 * This is the phase's headline deliverable, and it is deliberately the only
 * suite in the repo that runs the daemon the way an operator runs it: as a
 * real `node dist/cli.js daemon` PROCESS, configured only through its own
 * HTTP API, observed only through that API, its WebSocket, and the files on
 * disk. Nothing here reaches into the daemon's memory, and nothing here
 * calls `scan` or `run` after the daemon has started — that restraint IS the
 * test. If a file converges, it converged because the daemon decided to
 * converge it.
 *
 * What P2a's end-to-end test proved about `scan`/`run` by hand, this proves
 * about an unattended service, plus the three things only a service can be
 * wrong about: that a converged library STAYS converged across the daemon's
 * own repeated rescans and supervisor ticks (the defect that survived 987
 * green tests in P2a was exactly this — a file transcoded in round 1 and
 * re-transcoded in rounds 2, 3 and 4, for ever), that a flow edit brings
 * files back out of `good` without anybody asking, and that a file DROPPED
 * INTO A WATCHED FOLDER is picked up with no human command at all.
 *
 * Nothing in here asserts on elapsed time or on log text. Every wait polls a
 * CONDITION about observable state — a row through the API, a codec on disk,
 * a live pid — with a bounded deadline whose only job is to turn a hang into
 * a message that says what was being waited for.
 */

// The condition is computed SYNCHRONOUSLY at module scope because
// `describe.runIf` reads it at collection time, before any async `beforeAll`
// could run. A check that lived behind `beforeAll` silently skipped a whole
// suite in this repo for several commits, and a skipped suite is green.
// `ffmpegAvailableSync` answers `false` only for a genuine ENOENT and THROWS
// for every other failure (a spawn that failed under load, a non-zero exit),
// so an unreliable check fails this suite loudly instead of skipping the one
// suite that proves the product works.
const available = ffmpegAvailableSync();

/**
 * How long a convergence wait tolerates before calling itself a hang.
 *
 * Not a performance expectation — nothing here asserts on elapsed time — but
 * it does have to clear the product's own first retry backoff
 * (`BACKOFF_MINUTES[0]`, five minutes): a job that fails once, which a
 * machine running the whole suite in parallel with two live transcodes can
 * legitimately produce, is deliberately not retried until that backoff
 * expires. A deadline shorter than the backoff turns a designed retry into a
 * red suite.
 */
const CONVERGENCE_TIMEOUT_MS = 15 * 60 * 1000;

/** The daemon is run from its BUILT output, exactly as a real install runs it. */
const CLI_PATH = join(process.cwd(), 'packages/server/dist/cli.js');
const SERVER_SRC = join(process.cwd(), 'packages/server/src');

/** Newest mtime of any file under `dir`, recursively. */
const newestMtimeMs = (dir: string): number => {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    newest = Math.max(newest, entry.isDirectory() ? newestMtimeMs(full) : statSync(full).mtimeMs);
  }
  return newest;
};

/**
 * This suite spawns a BUILT artifact, so a regression in `src/` is invisible
 * here unless `pnpm build` ran first — and `tsc --build` is incremental, so
 * stale output is not regenerated by accident. Deliberately NOT gated on
 * `existsSync`: a missing or stale build must FAIL loudly rather than skip.
 */
const assertBuiltCliIsFresh = (): void => {
  if (!existsSync(CLI_PATH)) {
    throw new Error(`${CLI_PATH} does not exist. Run "pnpm build" before this suite.`);
  }
  const builtAt = statSync(CLI_PATH).mtimeMs;
  const newestSource = newestMtimeMs(SERVER_SRC);
  if (builtAt < newestSource) {
    throw new Error(
      `${CLI_PATH} (built ${new Date(builtAt).toISOString()}) is older than the newest file ` +
        `under packages/server/src (${new Date(newestSource).toISOString()}) — this suite would ` +
        `be running STALE compiled output. Run "pnpm build" (or "tsc --build --force") first.`,
    );
  }
};

/**
 * Waits for a condition about OBSERVABLE state, with a deadline that exists
 * only to turn a hang into a named failure. NOTHING is asserted about how
 * long anything took: the message says what was being waited for and what
 * was seen instead, because a bare timeout tells the next person nothing.
 */
const until = async (
  what: string,
  predicate: () => boolean | Promise<boolean>,
  options: { timeoutMs?: number; describe?: () => Promise<string> | string } = {},
): Promise<void> => {
  const timeoutMs = options.timeoutMs ?? 300_000;
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (await predicate()) return;
    if (Date.now() > deadline) {
      const detail =
        options.describe === undefined ? '' : `\nLast seen: ${await options.describe()}`;
      throw new Error(
        `Timed out after ${String(timeoutMs)}ms waiting for: ${what}.${detail}\n` +
          `(The deadline is a hang detector, not an expectation about speed.)`,
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
};

const isAlive = (pid: number): boolean => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

const makeSample = (path: string, seconds = 2) =>
  execFileAsync(
    'ffmpeg',
    [
      '-hide_banner',
      '-y',
      '-f',
      'lavfi',
      '-i',
      `testsrc=duration=${String(seconds)}:size=320x240:rate=10`,
      '-f',
      'lavfi',
      '-i',
      `sine=frequency=440:duration=${String(seconds)}`,
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-c:a',
      'aac',
      path,
    ],
    { maxBuffer: 10 * 1024 * 1024 },
  );

const videoCodecOf = async (path: string): Promise<string> => {
  const { stdout } = await execFileAsync('ffprobe', [
    '-v',
    'quiet',
    '-select_streams',
    'v:0',
    '-show_entries',
    'stream=codec_name',
    '-of',
    'csv=p=0',
    path,
  ]);
  return stdout.trim();
};

/** The full transcode-and-replace flow: exactly what a real deployment runs. */
const transcodeFlow = (quality: string): FlowDefinition => ({
  nodes: [
    { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'check',
      pluginId: 'trawlarr:checkVideoCodec',
      pluginVersion: '1.0.0',
      inputs: { codec: 'hevc' },
    },
    { id: 'begin', pluginId: 'trawlarr:beginCommand', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'encoder',
      pluginId: 'trawlarr:setVideoEncoder',
      pluginVersion: '1.0.0',
      inputs: { encoder: 'libx265', quality },
    },
    { id: 'execute', pluginId: 'trawlarr:execute', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'verify',
      pluginId: 'trawlarr:verifyOutput',
      pluginVersion: '1.0.0',
      inputs: { durationToleranceSeconds: '1', minSizeRatio: '0.05' },
    },
    {
      id: 'replace',
      pluginId: 'trawlarr:replaceOriginal',
      pluginVersion: '1.0.0',
      inputs: { trashRetentionDays: '14', allowCrossDevice: 'true' },
    },
  ],
  edges: [
    { fromNodeId: 'start', outputNumber: 1, toNodeId: 'check' },
    { fromNodeId: 'check', outputNumber: 2, toNodeId: 'begin' },
    { fromNodeId: 'begin', outputNumber: 1, toNodeId: 'encoder' },
    { fromNodeId: 'encoder', outputNumber: 1, toNodeId: 'execute' },
    { fromNodeId: 'execute', outputNumber: 1, toNodeId: 'verify' },
    { fromNodeId: 'verify', outputNumber: 1, toNodeId: 'replace' },
  ],
});

/**
 * Pulls the number out of `status`'s own `(NN% converged)` line — the same
 * falsifiable parse the CLI end-to-end suite uses, and for the same reason:
 * `'100% converged'` CONTAINS `'0% converged'`, so a substring check for the
 * latter can never fail.
 */
const convergencePercentOf = (stdout: string): number => {
  const match = /\((\d+)% converged\)/.exec(stdout);
  if (match?.[1] === undefined) {
    throw new Error(`Could not find a "(NN% converged)" line in status output:\n${stdout}`);
  }
  return Number.parseInt(match[1], 10);
};

interface StatsResource {
  total: number;
  /**
   * Named explicitly rather than indexed: the API always returns every
   * state, and spelling them out is what lets `byState.good` be a number
   * instead of `number | undefined` at every assertion below.
   */
  byState: {
    unknown: number;
    queued: number;
    running: number;
    good: number;
    failed: number;
    not_converging: number;
    held: number;
  };
  convergedPercent: number;
  paused: boolean;
  pausedReason: string | null;
}

describe.runIf(available)('daemon end-to-end: a library converges with nobody driving it', () => {
  let daemon: ChildProcess | null = null;
  let daemonOutput = '';

  afterEach(async () => {
    // A daemon left running would hold the next run's data directory and,
    // worse, keep transcoding into a temp tree nothing is watching.
    if (daemon !== null && daemon.exitCode === null && daemon.signalCode === null) {
      daemon.kill('SIGKILL');
      await new Promise((resolve) => daemon?.once('exit', resolve));
    }
    daemon = null;
  });

  it(
    'converges six files with no scan and no run, stays quiet, re-queues on a flow edit, ' +
      'picks up a dropped file through the watcher, honours a zero-worker schedule, ' +
      'and shuts down clean',
    async () => {
      assertBuiltCliIsFresh();

      const workDir = mkdtempSync(join(tmpdir(), 'trawlarr-daemon-e2e-'));
      const libraryRoot = join(workDir, 'library');
      const dataDir = join(workDir, 'data');
      mkdirSync(libraryRoot, { recursive: true });
      mkdirSync(dataDir, { recursive: true });

      // ---------------------------------------------------------------
      // Six h264 files, one with a companion .srt.
      // ---------------------------------------------------------------
      const moviePaths = [1, 2, 3, 4, 5, 6].map((n) => join(libraryRoot, `movie${String(n)}.mkv`));
      await Promise.all(moviePaths.map((path) => makeSample(path)));
      const companionPath = join(libraryRoot, 'movie1.srt');
      writeFileSync(companionPath, '1\n00:00:00,000 --> 00:00:01,000\nHello\n', 'utf8');
      for (const path of moviePaths) expect(await videoCodecOf(path)).toBe('h264');

      // The ONE thing written before the daemon starts, because there is no
      // API to write it to yet: the scan cadence. These are the daemon's own
      // settings (`scan.*`), the same values an operator edits in the UI —
      // shortened so the periodic-rescan backstop is exercised inside a test
      // run rather than in an hour. Nothing about libraries, flows,
      // schedules or work is pre-seeded: all of that goes through the API.
      {
        const db = openDatabase({ file: join(dataDir, 'trawlarr.db') });
        migrate(db);
        createSettingsRepo({ db }).setScan({
          watchEnabled: true,
          rescanIntervalMs: 5_000,
          settleMs: 500,
        });
        db.close();
      }

      // ---------------------------------------------------------------
      // Start the real daemon. From here to the shutdown at the end,
      // nothing in this test runs `scan` or `run`.
      // ---------------------------------------------------------------
      daemon = spawn('node', [CLI_PATH, 'daemon', '--data-dir', dataDir, '--port', '0'], {
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      daemon.stdout?.setEncoding('utf8');
      daemon.stderr?.setEncoding('utf8');
      daemon.stdout?.on('data', (chunk: string) => {
        daemonOutput += chunk;
      });
      daemon.stderr?.on('data', (chunk: string) => {
        daemonOutput += chunk;
      });
      const daemonPid = daemon.pid!;

      const lockPath = join(dataDir, DAEMON_LOCK_FILENAME);
      let record: DaemonRecord | null = null;
      await until(
        `the daemon to advertise itself in ${lockPath}`,
        () => {
          if (daemon?.exitCode !== null) {
            throw new Error(
              `The daemon exited with code ${String(daemon?.exitCode)} instead of starting. ` +
                `Its output was:\n${daemonOutput}`,
            );
          }
          if (!existsSync(lockPath)) return false;
          try {
            record = JSON.parse(readFileSync(lockPath, 'utf8')) as DaemonRecord;
          } catch {
            return false; // a partially written file; read it again
          }
          return typeof record.port === 'number' && record.port > 0;
        },
        { timeoutMs: 60_000, describe: () => daemonOutput },
      );
      const { port, apiKey } = record!;
      expect(record!.pid).toBe(daemonPid);

      const base = `http://127.0.0.1:${String(port)}/api/v1`;
      const api = async <T = unknown>(method: string, path: string, body?: unknown): Promise<T> => {
        const response = await fetch(`${base}${path}`, {
          method,
          headers: { 'x-api-key': apiKey, 'content-type': 'application/json' },
          body: body === undefined ? undefined : JSON.stringify(body),
        });
        const text = await response.text();
        if (!response.ok) {
          throw new Error(`${method} ${path} -> ${String(response.status)}: ${text}`);
        }
        return (text === '' ? null : JSON.parse(text)) as T;
      };

      // ---------------------------------------------------------------
      // The live event stream. `job.started`/`job.finished` are what prove
      // the concurrency bound, and they are the ONLY record of a worker's
      // ordering available from outside the daemon.
      // ---------------------------------------------------------------
      const events: TrawlarrEvent[] = [];
      const socket = new WebSocket(`ws://127.0.0.1:${String(port)}/api/v1/events`, {
        headers: { 'x-api-key': apiKey },
      });
      socket.on('message', (data: Buffer) => {
        events.push(JSON.parse(data.toString('utf8')) as TrawlarrEvent);
      });
      await new Promise<void>((resolve, reject) => {
        socket.once('open', resolve);
        socket.once('error', reject);
      });

      // Every pid the daemon ever reported for a worker, sampled from the
      // API while work is in flight. `job.started` carries a workerId, not a
      // pid, so GET /workers is the daemon's only surface that exposes one —
      // and the shutdown assertion needs pids.
      const workerPids = new Set<number>();
      const sampler = setInterval(() => {
        void (async () => {
          try {
            const status = await api<{ workers: { pid?: number }[] }>('GET', '/workers');
            for (const worker of status.workers) {
              if (typeof worker.pid === 'number') workerPids.add(worker.pid);
            }
          } catch {
            // The daemon is stopping, or the socket is closed. Sampling is
            // best-effort; every assertion below reads state directly.
          }
        })();
      }, 25);

      const stats = async (libraryId: string): Promise<StatsResource> =>
        await api<StatsResource>('GET', `/libraries/${libraryId}/stats`);
      const jobTotal = async (): Promise<number> =>
        (await api<{ total: number }>('GET', '/jobs?limit=1')).total;
      const fileTotal = async (libraryId: string): Promise<number> =>
        (await api<{ total: number }>('GET', `/files?libraryId=${libraryId}&limit=1`)).total;

      interface JobResource {
        id: string;
        fileId: string;
        state: string;
        outcome: string | null;
        logPath: string | null;
      }
      const allJobs = async (): Promise<JobResource[]> =>
        (await api<{ items: JobResource[] }>('GET', '/jobs?limit=500')).items;

      /**
       * How many times each file has been transcoded SUCCESSFULLY.
       *
       * The load-bearing count is this one, not the raw job total: "one
       * successful run per file per flow version" is the convergence claim,
       * and it stays true even on a machine where a transcode failed once and
       * the ledger's own five-minute backoff retried it. A raw-total
       * assertion would turn that designed retry into a red suite while
       * proving nothing extra — the "nothing ran at all" checks below use the
       * raw total, where exactness IS the property.
       */
      const successesPerFile = async (): Promise<Map<string, number>> => {
        const counts = new Map<string, number>();
        for (const job of await allJobs()) {
          if (job.state !== 'succeeded') continue;
          counts.set(job.fileId, (counts.get(job.fileId) ?? 0) + 1);
        }
        return counts;
      };

      /**
       * What a convergence wait says when it gives up: the library's counts,
       * and for every file that is not `good`, the row's own reason — its
       * attempt count, its backoff deadline, and the outcome its last job
       * recorded. A file that failed once is HELD for five minutes by design
       * (`BACKOFF_MINUTES`), which looks identical to a stuck queue unless
       * the message says so, and "timed out" on its own would send the next
       * person hunting for a defect that is not there.
       */
      const diagnose = async (libraryId: string): Promise<string> => {
        const counts = JSON.stringify(await stats(libraryId));
        const files = await api<{
          items: {
            id: string;
            path: string;
            state: string;
            attemptCount: number;
            holdUntilMs: number | null;
          }[];
        }>('GET', `/files?libraryId=${libraryId}&limit=500`);
        const lines: string[] = [];
        for (const file of files.items) {
          if (file.state === 'good') continue;
          const detail = await api<{ jobs: { state: string; outcome: string | null }[] }>(
            'GET',
            `/files/${file.id}`,
          );
          const last = detail.jobs[0];
          lines.push(
            `  ${basename(file.path)} state=${file.state} attempts=${String(file.attemptCount)} ` +
              `holdUntil=${file.holdUntilMs === null ? 'none' : new Date(file.holdUntilMs).toISOString()} ` +
              `lastJob=${last === undefined ? 'none' : `${last.state}: ${last.outcome ?? ''}`}`,
          );
        }
        return `${counts}\n${lines.join('\n')}`;
      };

      try {
        // -------------------------------------------------------------
        // Configure through the API, exactly as the UI would.
        // -------------------------------------------------------------
        const flow = await api<{ id: string }>('POST', '/flows', {
          name: 'HEVC',
          definition: transcodeFlow('30'),
        });
        const library = await api<{ id: string }>('POST', '/libraries', {
          name: 'Movies',
          roots: [libraryRoot],
        });
        await api('PATCH', `/libraries/${library.id}`, { flowId: flow.id });
        await api('PUT', '/system/schedule', {
          timezone: 'UTC',
          baseCounts: { transcode: 2, health: 0 },
          windows: [],
        });

        // =============================================================
        // 1. CONVERGENCE, UNATTENDED. No scan. No run. No requeue.
        // =============================================================
        await until(
          'the daemon to converge the library to 100% on its own (no scan, no run was issued)',
          async () => (await stats(library.id)).convergedPercent === 100,
          { timeoutMs: CONVERGENCE_TIMEOUT_MS, describe: async () => await diagnose(library.id) },
        );

        const converged = await stats(library.id);
        expect(converged.total).toBe(6);
        expect(converged.byState.good).toBe(6);
        expect(converged.byState.queued).toBe(0);
        expect(converged.byState.running).toBe(0);
        expect(converged.byState.failed).toBe(0);
        expect(converged.byState.not_converging).toBe(0);
        expect(converged.byState.held).toBe(0);

        // Read off disk with real ffprobe: the point of the product.
        for (const path of moviePaths) expect(await videoCodecOf(path)).toBe('hevc');

        // The six originals are recoverable, still h264, under names that
        // still identify which file they were.
        const trashDir = join(libraryRoot, '.trawlarr', 'trash');
        const trashed = readdirSync(trashDir);
        expect(trashed).toHaveLength(6);
        expect(trashed.map((name) => name.split('.')[0]!).sort()).toEqual(
          moviePaths.map((path) => basename(path, '.mkv')).sort(),
        );
        for (const name of trashed) {
          expect(name.endsWith('.mkv')).toBe(true);
          expect(await videoCodecOf(join(trashDir, name))).toBe('h264');
        }

        // The companion .srt is untouched, beside its media file, under its
        // ORIGINAL name — the filename belongs to the user.
        expect(existsSync(companionPath)).toBe(true);
        expect(statSync(companionPath).isFile()).toBe(true);
        expect(readdirSync(libraryRoot).filter((name) => name.endsWith('.srt'))).toEqual([
          'movie1.srt',
        ]);

        // Exactly six rows — no ghost row from a scan landing mid-replacement
        // while two workers ran — and exactly one SUCCESSFUL run per file: no
        // file was transcoded twice, which is the whole claim.
        expect(await fileTotal(library.id)).toBe(6);
        const firstPassSuccesses = await successesPerFile();
        expect(firstPassSuccesses.size).toBe(6);
        expect([...firstPassSuccesses.values()]).toEqual([1, 1, 1, 1, 1, 1]);
        // Nothing ended in a state nobody accounted for: a job is either a
        // success or a recorded failure that the ledger backed off and
        // retried, never a silent third thing.
        for (const job of await allJobs()) {
          expect(['succeeded', 'failed']).toContain(job.state);
        }

        // THE POINT OF THIS TASK: a real daemon, real forked workers, and the
        // log each one wrote is actually on disk and actually fetchable —
        // bytes on disk and the API's own response, never log text used as a
        // stand-in for behaviour.
        const jobWithLog = (await allJobs()).find((job) => job.logPath !== null);
        expect(jobWithLog).toBeDefined();
        expect(statSync(jobWithLog!.logPath!).size).toBeGreaterThan(0);
        const fetchedLog = await api<{ jobId: string; path: string; text: string }>(
          'GET',
          `/jobs/${jobWithLog!.id}/log`,
        );
        expect(fetchedLog.jobId).toBe(jobWithLog!.id);
        expect(fetchedLog.text.length).toBeGreaterThan(0);

        // Concurrency, from the ORDERED event stream rather than timestamps:
        // the schedule allowed two workers, so at no point were three jobs
        // in flight, and at some point there were two.
        let inFlight = 0;
        let maxInFlight = 0;
        for (const event of events) {
          if (event.type === 'job.started') inFlight += 1;
          if (event.type === 'job.finished') inFlight -= 1;
          maxInFlight = Math.max(maxInFlight, inFlight);
        }
        expect(maxInFlight).toBeLessThanOrEqual(2);
        expect(maxInFlight).toBe(2);

        // THE FRAME SHAPES A UI DEPENDS ON, pinned against a real daemon.
        // `packages/web/src/api/events.ts` hand-copies this union — it must,
        // because importing @trawlarr/server would drag better-sqlite3 and
        // node:child_process into a browser bundle's type graph — so nothing
        // but this check stops the two drifting. The key list is EXHAUSTIVE
        // on purpose: a field added here and not there renders as `undefined`
        // in the UI with no error anywhere, and a field removed here leaves
        // the copy describing something that no longer arrives.
        const kinds = new Set(events.map((frame) => frame.type));
        expect([...kinds]).toEqual(
          expect.arrayContaining(['job.started', 'job.progress', 'job.finished']),
        );
        const start = events.find((frame) => frame.type === 'job.started')!;
        expect(Object.keys(start).sort()).toEqual(
          ['fileId', 'jobId', 'libraryId', 'path', 'pid', 'type', 'workerId'].sort(),
        );

        // =============================================================
        // 2. THE SECOND PASS DOES NOTHING. This is what distinguishes
        //    "converged" from "did the work again and got the same
        //    answer" — the defect that survived all of P2a.
        // =============================================================
        const jobsAfterFirstPass = await jobTotal();

        // A deliberate rescan (the one human trigger this phase allows, and
        // only to prove idempotence — it is not what converged anything).
        const scansBefore = events.filter((event) => event.type === 'scan.finished').length;
        await api('POST', `/libraries/${library.id}/scan`);
        await until('a scan to finish after the manual rescan request', () => {
          return events.filter((event) => event.type === 'scan.finished').length > scansBefore;
        });
        const rescan = events.filter((event) => event.type === 'scan.finished').at(-1) as Extract<
          TrawlarrEvent,
          { type: 'scan.finished' }
        >;
        expect(rescan.summary.queued).toBe(0);
        expect(rescan.summary.alreadyGood).toBe(6);
        expect(rescan.summary.added).toBe(0);

        // And a supervisor tick, forced through the API rather than waited
        // out: re-PUTting the schedule reconciles the pool synchronously,
        // so "the supervisor looked at the queue and claimed nothing" is a
        // fact this call has already established when it returns.
        await api('PUT', '/system/schedule', {
          timezone: 'UTC',
          baseCounts: { transcode: 2, health: 0 },
          windows: [],
        });
        expect(await jobTotal()).toBe(jobsAfterFirstPass);
        expect((await stats(library.id)).byState.good).toBe(6);
        expect(await fileTotal(library.id)).toBe(6);

        // The daemon's OWN rescan cadence is 5s here, so several more of its
        // unattended passes run before this test ends; the final job count
        // at the bottom is the assertion that none of them re-did anything.

        // =============================================================
        // 3. THE OTHER DIRECTION: a flow edit must bring files back out
        //    of `good`, and the daemon must notice on its own. A fix
        //    that converged by never re-queueing would pass step 2 and
        //    destroy the feature.
        // =============================================================
        await api('PUT', `/flows/${flow.id}`, { definition: transcodeFlow('28') });

        await until(
          'the daemon to notice the edited flow and re-queue all six files by itself',
          async () => (await stats(library.id)).byState.good === 0,
          { describe: async () => await diagnose(library.id) },
        );
        const requeued = await stats(library.id);
        expect(requeued.byState.queued + requeued.byState.running).toBe(6);

        await until(
          'the six re-queued files to converge again under the edited flow',
          async () => (await stats(library.id)).convergedPercent === 100,
          { timeoutMs: CONVERGENCE_TIMEOUT_MS, describe: async () => await diagnose(library.id) },
        );
        // Each of the six has now converged exactly twice: once under the
        // original flow, once under the edited one. Still six rows.
        const reconvergedSuccesses = await successesPerFile();
        expect(reconvergedSuccesses.size).toBe(6);
        expect([...reconvergedSuccesses.values()]).toEqual([2, 2, 2, 2, 2, 2]);
        expect(await fileTotal(library.id)).toBe(6);
        for (const path of moviePaths) expect(await videoCodecOf(path)).toBe('hevc');

        // =============================================================
        // 4. A NEW FILE, PICKED UP BY THE WATCHER, WITH NO HUMAN.
        //    The periodic rescan is pushed out to ten minutes first, so
        //    that a file converged inside this test can ONLY have been
        //    noticed by the filesystem watcher.
        // =============================================================
        await api('PATCH', '/system/settings', { scan: { rescanIntervalMs: 600_000 } });
        const scansBeforeSlowdown = events.filter((event) => event.type === 'scan.finished').length;
        await until(
          'the already-armed 5s rescan to fire once more, re-arming itself at the new 10-minute ' +
            'interval — after this, only the watcher can trigger a scan',
          () =>
            events.filter((event) => event.type === 'scan.finished').length > scansBeforeSlowdown,
        );

        const newFile = join(libraryRoot, 'dropped.mkv');
        await makeSample(newFile);
        expect(await videoCodecOf(newFile)).toBe('h264');

        await until(
          'the watcher to notice dropped.mkv and the daemon to converge it with no manual scan ' +
            '(the periodic rescan is 10 minutes away, so nothing else could have found it)',
          async () => {
            const now = await stats(library.id);
            return now.total === 7 && now.convergedPercent === 100;
          },
          { timeoutMs: CONVERGENCE_TIMEOUT_MS, describe: async () => await diagnose(library.id) },
        );
        expect(await videoCodecOf(newFile)).toBe('hevc');
        expect(await fileTotal(library.id)).toBe(7);
        // The dropped file converged once; nothing else was re-run to do it.
        const withDropped = await successesPerFile();
        expect(withDropped.size).toBe(7);
        expect([...withDropped.values()].filter((count) => count === 2)).toHaveLength(6);
        expect([...withDropped.values()].filter((count) => count === 1)).toHaveLength(1);

        // =============================================================
        // 5. A ZERO-WORKER SCHEDULE STOPS NEW WORK AND DOES NOT
        //    INTERRUPT WORK IN PROGRESS.
        // =============================================================
        const longFile = join(libraryRoot, 'long.mkv');
        await makeSample(longFile, 45);

        let runningJobId = '';
        let runningPid = 0;
        await until(
          'the watcher to pick up long.mkv and a worker to start running it',
          async () => {
            const status = await api<{
              workers: { jobId: string | null; path: string | null; pid?: number }[];
            }>('GET', '/workers');
            const worker = status.workers.find((entry) => entry.path === longFile);
            if (worker === undefined || worker.jobId === null) return false;
            runningJobId = worker.jobId;
            runningPid = worker.pid ?? 0;
            return true;
          },
          { describe: async () => JSON.stringify(await api('GET', '/workers')) },
        );
        expect(runningPid).toBeGreaterThan(0);
        expect(isAlive(runningPid)).toBe(true);
        const jobsWithLongRunning = await jobTotal();

        // The window closes while that job is running.
        await api('PUT', '/system/schedule', {
          timezone: 'UTC',
          baseCounts: { transcode: 0, health: 0 },
          windows: [],
        });

        // Not cancelled: the worker is still there, on the same job, with
        // the same live pid, immediately after the schedule change returned
        // (and `PUT /system/schedule` awaits a full supervisor tick).
        const afterClose = await api<{
          workers: { jobId: string | null; pid?: number }[];
          target: Record<string, number>;
        }>('GET', '/workers');
        expect(afterClose.target.transcode).toBe(0);
        expect(afterClose.workers.map((worker) => worker.jobId)).toContain(runningJobId);
        expect(isAlive(runningPid)).toBe(true);

        // And nothing new starts, however much is queued: a second file is
        // requeued (which itself ticks the supervisor) and stays queued.
        const files = await api<{ items: { id: string; path: string }[] }>(
          'GET',
          `/files?libraryId=${library.id}&limit=500`,
        );
        const victim = files.items.find((file) => file.path === moviePaths[1])!;
        await api('POST', `/files/${victim.id}/requeue`);
        expect((await stats(library.id)).byState.queued).toBe(1);
        expect(await jobTotal()).toBe(jobsWithLongRunning);

        // The running job runs to completion — SUCCEEDED, not cancelled —
        // and its completion ticks the supervisor, which still starts
        // nothing because the target is zero.
        await until(
          'the in-progress transcode of long.mkv to finish on its own under a closed window',
          async () => {
            const detail = await api<{ job: { state: string } }>('GET', `/jobs/${runningJobId}`);
            return detail.job.state !== 'running';
          },
          { timeoutMs: 600_000 },
        );
        const finished = await api<{ job: { state: string; outcome: string | null } }>(
          'GET',
          `/jobs/${runningJobId}`,
        );
        expect(finished.job.state).toBe('succeeded');
        expect(await videoCodecOf(longFile)).toBe('hevc');
        expect(await jobTotal()).toBe(jobsWithLongRunning);
        expect((await api<{ active: number }>('GET', '/workers')).active).toBe(0);
        expect((await stats(library.id)).byState.queued).toBe(1);

        // =============================================================
        // 6. THE CLI, WHILE THE DAEMON OWNS THE DIRECTORY.
        // =============================================================
        const status = await execFileAsync('node', [CLI_PATH, 'status', '--data-dir', dataDir], {
          maxBuffer: 10 * 1024 * 1024,
        });
        expect(convergencePercentOf(status.stdout)).toBe(
          (await stats(library.id)).convergedPercent,
        );

        const refusal = await execFileAsync('node', [CLI_PATH, 'run', '--data-dir', dataDir], {
          maxBuffer: 10 * 1024 * 1024,
        }).then(
          () => null,
          (error: NodeJS.ErrnoException & { code?: number | string; stderr?: string }) => error,
        );
        expect(refusal).not.toBeNull();
        expect(refusal!.code).toBe(1);
        // The load-bearing half: the refusal is not cosmetic — no second
        // drainer claimed anything from the queue the daemon owns.
        expect(await jobTotal()).toBe(jobsWithLongRunning);
        expect((await stats(library.id)).byState.queued).toBe(1);
      } finally {
        clearInterval(sampler);
        socket.close();
      }

      // =============================================================
      // 7. SHUTDOWN: clean, with nothing left behind.
      // =============================================================
      const pidsSeen = [...workerPids];
      expect(pidsSeen.length).toBeGreaterThan(0);

      daemon.kill('SIGTERM');
      await until(
        'the daemon process to exit after SIGTERM',
        () => daemon?.exitCode !== null || daemon?.signalCode !== null,
        { timeoutMs: 120_000, describe: () => daemonOutput },
      );
      expect(daemon.exitCode).toBe(0);

      // The lock is gone, so the next command opens the database directly.
      expect(existsSync(join(dataDir, DAEMON_LOCK_FILENAME))).toBe(false);

      // No worker survives its daemon.
      for (const pid of pidsSeen) expect(isAlive(pid)).toBe(false);
      expect(isAlive(daemonPid)).toBe(false);

      // And no ffmpeg is still writing into this library. Matched on the
      // temp root, so a concurrent unrelated ffmpeg on the machine cannot
      // make this either pass or fail by accident.
      const { stdout: psOut } = await execFileAsync('ps', ['-eo', 'pid,args'], {
        maxBuffer: 10 * 1024 * 1024,
      });
      const strays = psOut
        .split('\n')
        .filter((line) => line.includes(workDir) && /ffmpeg|ffprobe/.test(line));
      expect(strays).toEqual([]);

      // =============================================================
      // 8. THE CLI REVERTS TO DIRECT DATABASE ACCESS, with the
      //    converged state intact — and can drain the one file left
      //    queued, which the daemon's closed window had refused to.
      // =============================================================
      {
        const db = openDatabase({ file: join(dataDir, 'trawlarr.db') });
        migrate(db);
        const libraryRow = createLibraryRepo(db).getByName('Movies')!;
        const counts = createMediaFileRepo(db).countsByState(libraryRow.id);
        expect(counts.good).toBe(7);
        expect(counts.queued).toBe(1);
        db.close();
      }

      const directStatus = await execFileAsync(
        'node',
        [CLI_PATH, 'status', '--data-dir', dataDir],
        { maxBuffer: 10 * 1024 * 1024 },
      );
      expect(convergencePercentOf(directStatus.stdout)).toBe(87); // 7 good of 8

      await execFileAsync('node', [CLI_PATH, 'run', '--data-dir', dataDir], {
        maxBuffer: 10 * 1024 * 1024,
      });
      const afterRun = await execFileAsync('node', [CLI_PATH, 'status', '--data-dir', dataDir], {
        maxBuffer: 10 * 1024 * 1024,
      });
      expect(convergencePercentOf(afterRun.stdout)).toBe(100);
      expect(await videoCodecOf(moviePaths[1]!)).toBe('hevc');
    },
    1_800_000,
  );
});
