import { execFile, spawn, type ChildProcess } from 'node:child_process';
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { afterEach, describe, expect, it } from 'vitest';
import {
  DAEMON_LOCK_FILENAME,
  DAEMON_OS_LOCK_FILENAME,
  readDaemonRecord,
  type DaemonRecord,
} from '../src/daemon/lockfile.js';

const execFileAsync = promisify(execFile);

/**
 * A KILLED DAEMON MUST NOT BRICK ITS DATA DIRECTORY — proved with real
 * processes, real SIGKILLs, and the built CLI.
 *
 * The failure this suite exists for is not hypothetical: a container is
 * killed rather than stopped (`docker kill`, an OOM kill, a host reboot,
 * `docker compose down -t 0`), the record on the `/config` volume survives
 * saying `"pid": 1`, and the replacement daemon — itself PID 1 — asked "is
 * pid 1 alive?", found ITSELF, and refused to start for ever.
 *
 * A pid cannot be tested for that outside a container (nothing here is PID
 * 1), so the shape is reproduced exactly: the record left behind by a
 * SIGKILLed daemon is rewritten to name a pid that IS alive and IS the
 * process doing the checking. Under the old pid heuristic that is
 * indistinguishable from a running daemon. Under a kernel lock it is a
 * corpse, because the kernel dropped the lock when the process died.
 *
 * The protection that must survive the fix is proved beside it: two daemons
 * that are BOTH alive on one data directory are still refused, because
 * turning a startup refusal into two writers on one SQLite file would be far
 * worse than the bug being fixed.
 *
 * Nothing here asserts on log text or elapsed time. Every assertion is about
 * observable state: an exit code, a process's liveness, the bytes in the
 * lock file, an HTTP response from the port the daemon says it is on.
 */

/** The daemon is run from its BUILT output, exactly as a real install runs it. */
const CLI_PATH = join(process.cwd(), 'packages/server/dist/cli.js');
const SERVER_SRC = join(process.cwd(), 'packages/server/src');

const newestMtimeMs = (dir: string): number => {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    newest = Math.max(newest, entry.isDirectory() ? newestMtimeMs(full) : statSync(full).mtimeMs);
  }
  return newest;
};

/**
 * This suite spawns a BUILT artifact, so a regression in `src/` is invisible
 * here unless `pnpm build` ran first — and `tsc --build` is incremental, so
 * stale output is not regenerated by accident. A missing or stale build must
 * FAIL loudly rather than skip.
 */
const assertBuiltCliIsFresh = (): void => {
  if (!existsSync(CLI_PATH)) {
    throw new Error(`${CLI_PATH} does not exist. Run "pnpm build" before this suite.`);
  }
  const builtAt = statSync(CLI_PATH).mtimeMs;
  const newestSource = newestMtimeMs(SERVER_SRC);
  if (builtAt < newestSource) {
    throw new Error(
      `${CLI_PATH} (built ${new Date(builtAt).toISOString()}) is older than the newest file ` +
        `under packages/server/src (${new Date(newestSource).toISOString()}) — this suite would ` +
        `be running STALE compiled output. Run "pnpm build" (or "tsc --build --force") first.`,
    );
  }
};

/** Waits for a condition about observable state; the deadline is a hang detector. */
const until = async (
  what: string,
  predicate: () => boolean | Promise<boolean>,
  options: { timeoutMs?: number; describe?: () => string } = {},
): Promise<void> => {
  const timeoutMs = options.timeoutMs ?? 60_000;
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (await predicate()) return;
    if (Date.now() > deadline) {
      const detail = options.describe === undefined ? '' : `\nLast seen: ${options.describe()}`;
      throw new Error(
        `Timed out after ${String(timeoutMs)}ms waiting for: ${what}.${detail}\n` +
          `(The deadline is a hang detector, not an expectation about speed.)`,
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
};

const isAlive = (pid: number): boolean => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

interface RunningDaemon {
  child: ChildProcess;
  pid: number;
  record: DaemonRecord;
  output: () => string;
}

const started: ChildProcess[] = [];

const newDataDir = (): string => mkdtempSync(join(tmpdir(), 'trawlarr-lockrec-'));

/** Spawn the real daemon and wait until it advertises the port it BOUND. */
const startDaemonProcess = async (dataDir: string): Promise<RunningDaemon> => {
  assertBuiltCliIsFresh();
  let output = '';
  const child = spawn('node', [CLI_PATH, 'daemon', '--data-dir', dataDir, '--port', '0'], {
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  started.push(child);
  child.stdout?.setEncoding('utf8');
  child.stderr?.setEncoding('utf8');
  const collect = (chunk: string): void => {
    output += chunk;
  };
  child.stdout?.on('data', collect);
  child.stderr?.on('data', collect);

  const lockPath = join(dataDir, DAEMON_LOCK_FILENAME);
  let record: DaemonRecord | null = null;
  await until(
    `the daemon to advertise itself in ${lockPath}`,
    () => {
      if (child.exitCode !== null) {
        throw new Error(
          `The daemon exited with code ${String(child.exitCode)} instead of starting. ` +
            `Its output was:\n${output}`,
        );
      }
      if (!existsSync(lockPath)) return false;
      try {
        record = JSON.parse(readFileSync(lockPath, 'utf8')) as DaemonRecord;
      } catch {
        return false; // a partially written file; read it again
      }
      return typeof record.port === 'number' && record.port > 0 && record.pid === child.pid;
    },
    { describe: () => output },
  );

  // The record is written the moment the socket is up, which is BEFORE the
  // daemon has finished starting and installed its SIGTERM handler — a signal
  // delivered in that window kills the process outright, with no shutdown
  // path, and this suite would be timing a race rather than testing one. The
  // CLI writes its startup banner only after `startDaemon()` has resolved, so
  // waiting for any stdout at all is waiting for "fully started". Nothing is
  // asserted about what the banner says.
  await until(
    'the daemon to finish starting (its startup banner on stdout)',
    () => output.length > 0,
    { describe: () => output },
  );

  return { child, pid: child.pid!, record: record!, output: () => output };
};

/** SIGKILL: no shutdown path runs, so the record is left behind exactly as a `docker kill` leaves it. */
const kill9 = async (daemon: RunningDaemon): Promise<void> => {
  daemon.child.kill('SIGKILL');
  await until(`pid ${String(daemon.pid)} to be gone`, () => !isAlive(daemon.pid));
};

const health = async (port: number): Promise<number> =>
  (await fetch(`http://127.0.0.1:${String(port)}/api/v1/system/health`)).status;

const readRecordFile = (dataDir: string): DaemonRecord =>
  JSON.parse(readFileSync(join(dataDir, DAEMON_LOCK_FILENAME), 'utf8')) as DaemonRecord;

interface CliResult {
  code: number;
  stdout: string;
  stderr: string;
}

const cli = async (args: string[]): Promise<CliResult> => {
  try {
    const { stdout, stderr } = await execFileAsync('node', [CLI_PATH, ...args], {
      maxBuffer: 10 * 1024 * 1024,
    });
    return { code: 0, stdout, stderr };
  } catch (error) {
    const failure = error as { code?: number; stdout?: string; stderr?: string };
    return { code: failure.code ?? 1, stdout: failure.stdout ?? '', stderr: failure.stderr ?? '' };
  }
};

afterEach(async () => {
  while (started.length > 0) {
    const child = started.pop()!;
    if (child.exitCode === null && child.signalCode === null) {
      child.kill('SIGKILL');
      await until(`pid ${String(child.pid!)} to be gone`, () => !isAlive(child.pid!));
    }
  }
});

describe('a data directory whose daemon was killed', () => {
  it('is taken over by the next daemon even when the record names a live pid', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);
    await kill9(first);

    // The record survived, as it does on a `/config` volume. Rewrite the pid
    // to one that is unquestionably ALIVE and is the process asking — the
    // container case, where the dead daemon was PID 1 and so is the new one.
    const stale = readRecordFile(dataDir);
    writeFileSync(
      join(dataDir, DAEMON_LOCK_FILENAME),
      JSON.stringify({ ...stale, pid: process.pid }),
      'utf8',
    );
    expect(isAlive(process.pid)).toBe(true);

    // Under the pid heuristic this start refused, permanently.
    const second = await startDaemonProcess(dataDir);

    expect(readRecordFile(dataDir).pid).toBe(second.pid);
    expect(await health(second.record.port)).toBe(200);
  });

  it('is reported as unowned to any other process, so the CLI stops dialling a dead port', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);
    const deadPort = first.record.port;
    await kill9(first);

    writeFileSync(
      join(dataDir, DAEMON_LOCK_FILENAME),
      JSON.stringify({ ...readRecordFile(dataDir), pid: process.pid }),
      'utf8',
    );

    // This process is not the one that held the lock, and never was: the
    // answer comes from the kernel, not from a descriptor this process owns.
    expect(await readDaemonRecord({ dataDir })).toBeNull();

    // And the CLI, in a THIRD process, opens the database directly rather
    // than refusing or dialling the port nothing is listening on any more.
    const status = await cli(['status', '--data-dir', dataDir]);
    expect(status.code).toBe(0);
    await expect(
      fetch(`http://127.0.0.1:${String(deadPort)}/api/v1/system/health`),
    ).rejects.toThrow();
  });

  it('leaves the lock file itself behind for the successor to lock again', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);
    await kill9(first);
    expect(existsSync(join(dataDir, DAEMON_OS_LOCK_FILENAME))).toBe(true);

    const second = await startDaemonProcess(dataDir);
    expect(existsSync(join(dataDir, DAEMON_OS_LOCK_FILENAME))).toBe(true);
    expect(readRecordFile(dataDir).pid).toBe(second.pid);
  });
});

describe('two live daemons on one data directory', () => {
  it('are still refused: the second exits non-zero, naming the first', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);

    const second = await cli(['daemon', '--data-dir', dataDir, '--port', '0']);

    expect(second.code).not.toBe(0);
    expect(second.stderr).toContain(String(first.pid));
    // The incumbent is untouched and still serving.
    expect(readRecordFile(dataDir).pid).toBe(first.pid);
    expect(isAlive(first.pid)).toBe(true);
    expect(await health(first.record.port)).toBe(200);
  });

  it('refuses the second even when the record on disk was tampered with', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);

    // Ownership is the kernel lock, not the file: a record naming a dead pid
    // must not let a second daemon in beside a live one.
    writeFileSync(
      join(dataDir, DAEMON_LOCK_FILENAME),
      JSON.stringify({ ...readRecordFile(dataDir), pid: 999_999 }),
      'utf8',
    );

    const second = await cli(['daemon', '--data-dir', dataDir, '--port', '0']);
    expect(second.code).not.toBe(0);
    expect(isAlive(first.pid)).toBe(true);
    expect(await health(first.record.port)).toBe(200);
  });

  it('keeps a CLI in another process out of the database while one is live', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);

    const run = await cli(['run', '--data-dir', dataDir]);
    expect(run.code).not.toBe(0);
    expect(run.stderr).toContain(String(first.pid));
  });
});

describe('a daemon that shuts down cleanly', () => {
  it('releases the lock and removes its record, so the next one starts', async () => {
    const dataDir = newDataDir();
    const first = await startDaemonProcess(dataDir);

    first.child.kill('SIGTERM');
    await until(`pid ${String(first.pid)} to exit`, () => !isAlive(first.pid));
    expect(existsSync(join(dataDir, DAEMON_LOCK_FILENAME))).toBe(false);
    expect(await readDaemonRecord({ dataDir })).toBeNull();

    const second = await startDaemonProcess(dataDir);
    expect(readRecordFile(dataDir).pid).toBe(second.pid);
    expect(await health(second.record.port)).toBe(200);
  });
});
