import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';
import { extractFacts, type FlowDefinition } from '@trawlarr/core';
import type { ProbeData } from '@trawlarr/plugin-api';
import { openDatabase, type Db } from '../src/db/connection.js';
import { migrate } from '../src/db/migrate.js';
import { createFlowRepo } from '../src/db/flow-repo.js';
import { createLibraryRepo } from '../src/db/library-repo.js';
import { createMediaFileRepo, type MediaFileRow } from '../src/db/media-file-repo.js';
import { createSettingsRepo } from '../src/db/settings-repo.js';
import { scanLibrary } from '../src/scanner/scan-library.js';
import { createAgentHandle, forkAgent } from '../src/worker/agent-handle.js';
import { createEventBus } from '../src/daemon/events.js';
import { createSupervisor, type CreateAgentFn } from '../src/daemon/supervisor.js';
import { ffmpegAvailableSync } from '../../../test-support/tool-availability.js';

const execFileAsync = promisify(execFile);

/**
 * TWO WORKERS, FOR REAL.
 *
 * Everything about the supervisor's arithmetic is proved deterministically
 * against fake agents in `src/daemon/supervisor.test.ts`. What only real
 * forked workers can prove is the agreement between the pieces: that two
 * processes replacing files at the same time still leave one row per file,
 * that a scan running CONCURRENTLY with them does not open a phantom row for
 * an in-flight output, and — the one this suite exists for — that a worker
 * killed the way an OOM killer kills one leaves its file CLAIMABLE rather
 * than stranded in `running`.
 *
 * The condition is computed synchronously at module scope on purpose: a
 * `describe.runIf` whose condition lives behind an async `beforeAll` reads
 * as `undefined` at collection time and silently skips the whole suite.
 */
const ffmpegAvailable = ffmpegAvailableSync();

const AGENT_DIST = join(process.cwd(), 'packages/server/dist/worker/agent.js');
const AGENT_SRC = join(process.cwd(), 'packages/server/src/worker/agent.ts');

/**
 * These suites fork a BUILT artifact, so `pnpm test` alone proves nothing
 * about `src/` unless `pnpm build` ran first — and `tsc --build` is
 * incremental, so a stale output is not regenerated by accident.
 * Deliberately NOT gated on `existsSync`: a missing artifact must FAIL here,
 * loudly, rather than skip and report green.
 */
const assertBuiltAgentIsFresh = (): void => {
  if (!existsSync(AGENT_DIST)) {
    throw new Error(`${AGENT_DIST} does not exist. Run "pnpm build" before this suite.`);
  }
  const builtAt = statSync(AGENT_DIST).mtimeMs;
  const sourceAt = statSync(AGENT_SRC).mtimeMs;
  if (builtAt < sourceAt) {
    throw new Error(
      `${AGENT_DIST} (built ${new Date(builtAt).toISOString()}) is older than ` +
        `${AGENT_SRC} (${new Date(sourceAt).toISOString()}) — this suite would be forking ` +
        `STALE compiled output. Run "pnpm build" (or "tsc --build --force") first.`,
    );
  }
};

/**
 * The production agent factory, pointed at the built agent.
 *
 * The seam substitutes only the PATH: this is the real `createAgentHandle`,
 * with the real `forkAgent` and its real `detached`/`stdio` options, because
 * `AGENT_MODULE_URL` resolves against this repo's TypeScript source layout
 * under vitest.
 */
const realAgents: CreateAgentFn = (input) =>
  createAgentHandle({
    id: input.id,
    documents: input.documents,
    onStep: input.onStep,
    onHeartbeat: input.onHeartbeat,
    onProgress: input.onProgress,
    onLog: input.onLog,
    nowMs: input.nowMs,
    forkFn: () => forkAgent(AGENT_DIST),
  });

/**
 * Waits for a condition about OBSERVABLE state (a row, a file, a live
 * process), with a deadline that exists only to turn a hang into a named
 * failure. Nothing is ASSERTED about how long anything took.
 */
const until = async (
  what: string,
  predicate: () => boolean | Promise<boolean>,
  timeoutMs = 120_000,
): Promise<void> => {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (await predicate()) return;
    if (Date.now() > deadline) throw new Error(`Timed out waiting for: ${what}`);
    await new Promise((resolve) => setTimeout(resolve, 25));
  }
};

const isAlive = (pid: number): boolean => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

const rowsOf = (db: Db, libraryId: string): MediaFileRow[] =>
  createMediaFileRepo(db).listByLibrary({ libraryId });

const makeSample = (path: string) =>
  execFileAsync('ffmpeg', [
    '-hide_banner',
    '-y',
    '-f',
    'lavfi',
    '-i',
    'testsrc=duration=2:size=160x120:rate=10',
    '-c:v',
    'libx264',
    '-preset',
    'ultrafast',
    path,
  ]);

const videoCodecOf = async (path: string): Promise<string> => {
  const { stdout } = await execFileAsync('ffprobe', [
    '-v',
    'quiet',
    '-select_streams',
    'v:0',
    '-show_entries',
    'stream=codec_name',
    '-of',
    'csv=p=0',
    path,
  ]);
  return stdout.trim();
};

/** The full transcode-and-replace flow: exactly what a real deployment runs. */
const transcodeFlow = (): FlowDefinition => ({
  nodes: [
    { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'check',
      pluginId: 'trawlarr:checkVideoCodec',
      pluginVersion: '1.0.0',
      inputs: { codec: 'hevc' },
    },
    { id: 'begin', pluginId: 'trawlarr:beginCommand', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'encoder',
      pluginId: 'trawlarr:setVideoEncoder',
      pluginVersion: '1.0.0',
      inputs: { encoder: 'libx265', quality: '30' },
    },
    { id: 'execute', pluginId: 'trawlarr:execute', pluginVersion: '1.0.0', inputs: {} },
    {
      id: 'verify',
      pluginId: 'trawlarr:verifyOutput',
      pluginVersion: '1.0.0',
      inputs: { durationToleranceSeconds: '1', minSizeRatio: '0.05' },
    },
    {
      id: 'replace',
      pluginId: 'trawlarr:replaceOriginal',
      pluginVersion: '1.0.0',
      inputs: { trashRetentionDays: '14', allowCrossDevice: 'true' },
    },
  ],
  edges: [
    { fromNodeId: 'start', outputNumber: 1, toNodeId: 'check' },
    { fromNodeId: 'check', outputNumber: 2, toNodeId: 'begin' },
    { fromNodeId: 'begin', outputNumber: 1, toNodeId: 'encoder' },
    { fromNodeId: 'encoder', outputNumber: 1, toNodeId: 'execute' },
    { fromNodeId: 'execute', outputNumber: 1, toNodeId: 'verify' },
    { fromNodeId: 'verify', outputNumber: 1, toNodeId: 'replace' },
  ],
});

const daemonFor = (db: Db, dataDir: string) => {
  const bus = createEventBus();
  const settings = createSettingsRepo({ db });
  const supervisor = createSupervisor({
    db,
    bus,
    settings,
    dataDir,
    nowMs: () => Date.now(),
    createAgent: realAgents,
  });
  return { bus, settings, supervisor };
};

describe.runIf(ffmpegAvailable)('two workers converge a library', () => {
  it('transcodes four files with two concurrent workers, while a scan runs alongside them', async () => {
    assertBuiltAgentIsFresh();

    const workDir = mkdtempSync(join(tmpdir(), 'trawlarr-two-workers-'));
    const root = join(workDir, 'library');
    mkdirSync(root, { recursive: true });

    const paths = [
      join(root, 'movie1.mkv'),
      join(root, 'movie2.mkv'),
      join(root, 'movie3.mkv'),
      join(root, 'movie4.mkv'),
    ];
    await Promise.all(paths.map((path) => makeSample(path)));
    for (const path of paths) expect(await videoCodecOf(path)).toBe('h264');

    const db = openDatabase({ file: join(workDir, 'trawlarr.db') });
    migrate(db);

    const flow = createFlowRepo(db).create({
      name: 'HEVC',
      definition: transcodeFlow(),
      nowMs: Date.now(),
    });
    const library = createLibraryRepo(db).create({
      name: 'Movies',
      roots: [root],
      flowId: flow.id,
      nowMs: Date.now(),
    });

    const { settings, supervisor } = daemonFor(db, workDir);
    settings.setHardware({ available: ['cpu'], caps: {} });
    settings.setSchedule({
      timezone: 'UTC',
      baseCounts: { transcode: 2, health: 0 },
      windows: [],
    });

    await scanLibrary({
      db,
      libraryId: library.id,
      ffprobePath: 'ffprobe',
      nowMs: () => Date.now(),
    });
    expect(createMediaFileRepo(db).countsByState(library.id).queued).toBe(4);

    // The pool refills itself as each job completes, so one tick starts the
    // whole drain. Two workers, four files.
    await supervisor.tick();
    expect(supervisor.status().workers).toHaveLength(2);

    // 7. A scan running CONCURRENTLY with two workers replacing files. This
    // is the regression test for the in-flight-output guard under N
    // workers: `listRunningPaths` is read fresh per walked file, so a job
    // that started after this scan began is still covered. Cache it for the
    // length of a scan and this suite goes red with a fifth row whose path
    // points inside `.trawlarr`.
    const concurrentScan = scanLibrary({
      db,
      libraryId: library.id,
      ffprobePath: 'ffprobe',
      nowMs: () => Date.now(),
    });

    await until(
      'the queue to drain and every worker to retire',
      () =>
        supervisor.status().workers.length === 0 &&
        createMediaFileRepo(db).countsByState(library.id).queued === 0,
      600_000,
    );
    await concurrentScan;

    // 4. Every library file is hevc now — read off disk with real ffprobe.
    for (const path of paths) expect(await videoCodecOf(path)).toBe('hevc');

    // 5. Exactly four rows. Two workers replacing files while a scan runs is
    // exactly the shape that once produced two `good` rows for one file —
    // "100% converged", one of them a phantom whose content lived only in
    // trash.
    const rows = rowsOf(db, library.id);
    expect(rows).toHaveLength(4);
    expect(new Set(rows.map((row) => row.path)).size).toBe(4);
    for (const row of rows) expect(row.path.includes('.trawlarr')).toBe(false);
    expect(createMediaFileRepo(db).countsByState(library.id).good).toBe(4);

    // 6. Exactly four job rows, one per file id.
    const jobs = db.prepare(`SELECT file_id FROM job`).all() as { file_id: string }[];
    expect(jobs).toHaveLength(4);
    expect(new Set(jobs.map((job) => job.file_id)).size).toBe(4);

    db.close();
  }, 900_000);
});

/**
 * The in-flight-output guard, FORCED rather than raced.
 *
 * Test 1 above runs a scan alongside two real workers, which is the shape
 * that once produced a phantom row — but a race that has to happen on its
 * own is a race that mostly misses, and a scan that walks four files in
 * milliseconds finishes long before an encode lands. Reverting
 * `listRunningPaths` to a per-scan cache leaves test 1 GREEN.
 *
 * So this test forces the interleaving through `scanLibrary`'s own
 * `onProgress` hook: the replacement is already on disk when the scan
 * starts, and the row is committed `running` DURING the walk — a job that
 * started after this scan began, which is precisely the case a cached list
 * cannot cover. Cache it and this test opens a third row for a file that is
 * some other run's output.
 */
describe.runIf(ffmpegAvailable)('a scan that starts before the claim it has to respect', () => {
  it('leaves an in-flight output alone when the claim lands mid-walk', async () => {
    const workDir = mkdtempSync(join(tmpdir(), 'trawlarr-inflight-'));
    const root = join(workDir, 'library');
    mkdirSync(root, { recursive: true });

    const original = join(root, 'movie1.mkv');
    await makeSample(original);
    await makeSample(join(root, 'movie2.mkv'));

    const db = openDatabase({ file: join(workDir, 'trawlarr.db') });
    migrate(db);
    const flow = createFlowRepo(db).create({
      name: 'HEVC',
      definition: transcodeFlow(),
      nowMs: Date.now(),
    });
    const library = createLibraryRepo(db).create({
      name: 'Movies',
      roots: [root],
      flowId: flow.id,
      nowMs: Date.now(),
    });

    const mediaFileRepo = createMediaFileRepo(db);
    await scanLibrary({
      db,
      libraryId: library.id,
      ffprobePath: 'ffprobe',
      nowMs: () => Date.now(),
    });
    expect(rowsOf(db, library.id)).toHaveLength(2);

    // A run's replacement, already on disk beside the file it replaces:
    // same directory, same stem, different container — and genuinely
    // different CONTENT, so identity cannot match it to the original's row.
    const replacement = join(root, 'movie1.mp4');
    await execFileAsync('ffmpeg', [
      '-hide_banner',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=3:size=160x120:rate=10',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      replacement,
    ]);

    const originalRow = rowsOf(db, library.id).find((row) => row.path === original)!;
    let committedDuringWalk = 0;
    await scanLibrary({
      db,
      libraryId: library.id,
      ffprobePath: 'ffprobe',
      nowMs: () => Date.now(),
      onProgress: (seen) => {
        // The claim happens AFTER this scan began — the case the fresh read
        // exists for. Committed exactly once, on the first file walked.
        if (seen !== 1 || committedDuringWalk > 0) return;
        committedDuringWalk += 1;
        mediaFileRepo.setState({ fileId: originalRow.id, state: 'running' });
      },
    });

    expect(committedDuringWalk).toBe(1);
    expect(mediaFileRepo.getById(originalRow.id)?.state).toBe('running');

    // Still two rows: the replacement is some run's output, not a new file.
    const rows = rowsOf(db, library.id);
    expect(rows).toHaveLength(2);
    expect(rows.map((row) => row.path).sort()).toEqual([original, join(root, 'movie2.mkv')].sort());

    db.close();
  }, 300_000);
});

/**
 * A CommonJS plugin that announces itself and then never returns.
 *
 * It stands in for the middle of a two-hour transcode: the row is `running`,
 * a real child process is holding it, and nothing is going to finish it on
 * its own. The marker file is how the test knows the job is genuinely in
 * flight — observable state, not a sleep.
 */
const hangingPluginPath = (markerDir: string): string => {
  const dir = mkdtempSync(join(tmpdir(), 'trawlarr-hang-plugin-'));
  const abs = join(dir, 'index.js');
  writeFileSync(
    abs,
    `
const fs = require('node:fs');
const path = require('node:path');

const details = () => ({
  name: 'Hang',
  description: 'never returns, standing in for a long transcode',
  style: { borderColor: '#000000' },
  tags: 'test',
  isStartPlugin: false,
  pType: '',
  sidebarPosition: 1,
  icon: 'faQuestion',
  inputs: [],
  outputs: [{ number: 1, tooltip: 'out 1' }],
  requiresVersion: '1.0.0',
});

const plugin = async (args) => {
  // Written through the SAME jobLog seam a real plugin's progress lines use,
  // so it lands in the on-disk job log via the SYNCHRONOUS writer before the
  // marker file even exists — proving the SIGKILL below cannot outrun it.
  args.jobLog('hanging plugin: about to hang');
  fs.writeFileSync(path.join(${JSON.stringify(markerDir)}, 'started-' + process.pid), '');
  await new Promise(() => {});
  return { outputNumber: 1, outputFileObj: args.inputFileObj, variables: args.variables };
};

module.exports = { details, plugin };
`,
    'utf8',
  );
  return abs;
};

const PROBE: ProbeData = {
  streams: [
    { index: 0, codec_type: 'video', codec_name: 'h264', width: 1920, height: 1080 },
    { index: 1, codec_type: 'audio', codec_name: 'aac' },
  ],
  format: { duration: '60.0', size: '4096', bit_rate: '16384' },
};

/**
 * THE SEAM THIS TASK EXISTS FOR.
 *
 * `agent-handle.test.ts` proves a vanished child produces
 * `AgentFailure.reported: false`, and `apply-report.ts` documents that both
 * failure paths reach `applyStall` so the row leaves `running`. Until now
 * nothing joined those two facts up, because nothing wired the agent handle
 * to a daemon-side loop — and "each side is correct" is exactly the shape of
 * the three seam bugs this project has already shipped, one of which was a
 * library that silently never converged.
 *
 * So: a REAL forked worker, a REAL job in flight, SIGKILL — which is what an
 * OOM kill looks like, and transcoding makes that realistic — and then the
 * assertion is on the DATABASE ROW, not on the `AgentFailure`. `reported:
 * false` is a protocol fact; "this file can be claimed again" is the
 * consequence that actually matters.
 */
describe('a worker killed mid-job', () => {
  it('leaves its file claimable, with the attempt counted, and the pool keeps going', async () => {
    assertBuiltAgentIsFresh();

    const workDir = mkdtempSync(join(tmpdir(), 'trawlarr-oom-'));
    const root = join(workDir, 'library');
    const markerDir = join(workDir, 'markers');
    mkdirSync(root, { recursive: true });
    mkdirSync(markerDir, { recursive: true });

    const db = openDatabase({ file: join(workDir, 'trawlarr.db') });
    migrate(db);

    const flow = createFlowRepo(db).create({
      name: 'Hang',
      definition: {
        nodes: [
          { id: 'start', pluginId: 'trawlarr:start', pluginVersion: '1.0.0', inputs: {} },
          {
            id: 'hang',
            pluginId: hangingPluginPath(markerDir),
            pluginVersion: '1.0.0',
            inputs: {},
          },
        ],
        edges: [{ fromNodeId: 'start', outputNumber: 1, toNodeId: 'hang' }],
      },
      nowMs: Date.now(),
    });
    const library = createLibraryRepo(db).create({
      name: 'Movies',
      roots: [root],
      flowId: flow.id,
      nowMs: Date.now(),
    });

    // Two files, one worker: the second file is what proves the pool carried
    // on rather than dying with the child.
    const mediaFileRepo = createMediaFileRepo(db);
    const fileIds = [0, 1].map((index) => {
      const path = join(root, `movie${String(index)}.mkv`);
      writeFileSync(path, `not really a movie ${String(index)}`, 'utf8');
      const fileId = mediaFileRepo.upsertScanned({
        libraryId: library.id,
        identity: {
          inodeKey: `2049:${String(100 + index)}`,
          contentKey: `4096:${String(index)}:ff`,
        },
        path,
        nlink: 1,
        sizeBytes: 4096,
        mtimeMs: Date.now(),
        ctimeMs: Date.now(),
        container: 'mkv',
        nowMs: Date.now(),
      });
      mediaFileRepo.setProbe({
        fileId,
        probe: PROBE,
        facts: extractFacts({ probe: PROBE, container: 'mkv', sizeBytes: 4096 }),
      });
      mediaFileRepo.setState({ fileId, state: 'queued' });
      return fileId;
    });

    const { settings, supervisor } = daemonFor(db, workDir);
    settings.setHardware({ available: ['cpu'], caps: {} });
    settings.setSchedule({
      timezone: 'UTC',
      baseCounts: { transcode: 1, health: 0 },
      windows: [],
    });

    await supervisor.tick();

    const first = supervisor.status().workers[0];
    expect(first).toBeDefined();
    const victimFileId = first!.fileId!;
    const victimPid = first!.pid!;
    expect(victimPid).toBeGreaterThan(0);

    // The claim committed `running` in the DAEMON, before the fork — the
    // ordering the scanner's in-flight-output guard depends on.
    expect(mediaFileRepo.getById(victimFileId)?.state).toBe('running');

    await until('the worker to reach the middle of its job', () =>
      existsSync(join(markerDir, `started-${String(victimPid)}`)),
    );
    expect(isAlive(victimPid)).toBe(true);

    // An OOM kill, exactly: no cancel, no protocol message, no chance to
    // author a failure. The child simply stops existing.
    process.kill(victimPid, 'SIGKILL');

    await until('the killed worker to be reaped and its row written back', () => {
      const row = mediaFileRepo.getById(victimFileId);
      return row !== null && row.state !== 'running';
    });
    expect(isAlive(victimPid)).toBe(false);

    // THE ASSERTION THIS TEST EXISTS FOR — the row, not the AgentFailure.
    const victimRow = mediaFileRepo.getById(victimFileId)!;
    expect(victimRow.state).toBe('held');
    // Counted as an attempt, so the backoff applies and a file that kills
    // its worker every time cannot spin forever.
    expect(victimRow.attempt_count).toBe(1);
    expect(victimRow.hold_until_ms).not.toBeNull();

    // The job row closed too: no attempt is left open with no explanation.
    const victimJob = db.prepare(`SELECT * FROM job WHERE file_id = ?`).get(victimFileId) as {
      state: string;
      ended_at: number | null;
      log_path: string | null;
    };
    expect(victimJob.state).toBe('failed');
    expect(victimJob.ended_at).not.toBeNull();

    // THE SIGKILL PROOF: the daemon allocated this path before the fork, and
    // the AGENT — not the daemon — wrote to it synchronously, on its way to
    // the hang. A SIGKILL leaves no chance to flush a buffer or send one more
    // IPC frame, so bytes on disk here can only have come from `writeSync`
    // inside the child before the kernel tore it down.
    expect(victimJob.log_path).not.toBeNull();
    expect(statSync(victimJob.log_path!).size).toBeGreaterThan(0);
    expect(readFileSync(victimJob.log_path!, 'utf8')).toContain('hanging plugin: about to hang');

    // And the pool carried on: the OTHER file is now claimed and running in
    // a NEW process. A supervisor that died with its child would leave this
    // file queued for ever.
    await until('the freed slot to be refilled', () => supervisor.status().workers.length === 1);
    const successor = supervisor.status().workers[0]!;
    expect(successor.fileId).toBe(fileIds.find((id) => id !== victimFileId));
    expect(successor.pid).not.toBe(victimPid);
    expect(mediaFileRepo.getById(successor.fileId!)?.state).toBe('running');

    // Clean up the second hanging worker the same way, and let the
    // supervisor write it back rather than leaking a process.
    await until('the successor to reach the middle of its job', () =>
      existsSync(join(markerDir, `started-${String(successor.pid!)}`)),
    );
    supervisor.pause();
    process.kill(successor.pid!, 'SIGKILL');
    await supervisor.drain();

    expect(supervisor.status().workers).toHaveLength(0);
    expect(rowsOf(db, library.id).every((row) => row.state === 'held')).toBe(true);

    db.close();
  }, 180_000);
});
